interlay/interbtc

crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/tests/mock.rs
parachain/runtime/tests/test_redeem.rs
parachain/runtime/tests/test_replace.rs

Two distinct changes, but since they overlap I made it into 1 PR. I suggest to look at the individual commits.
First change is a change to how liquidation works. We discussed earlier that we keep `collateral * (to-be-redeem /  issued)` in the vault, and slash the rest to the liquidation vault. However, I think it changed it to `collateral * (to-be-redeem /  (issued + to-be-issued)`, since at the time of slashing, the collateral is used to potentially back `issued + to-be-issued` tokens.
The second change fixes liquidation_redeem according to the discussions.

fix: liquidation & liquidation_redeem

---

crates/vault-registry/src/ext.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/src/lib.rs

fix: only use backing collateral for get_total_collateralization

---

crates/issue/src/benchmarking.rs
crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/redeem/src/ext.rs
crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/refund/src/ext.rs
crates/refund/src/lib.rs
crates/refund/src/tests.rs
crates/replace/src/benchmarking.rs
crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/replace/src/tests.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/tests/mock/mod.rs
parachain/runtime/tests/test_redeem.rs

The vault type in `types.rs` is simplified - it no longer does any sort of checks like the secure threshold check. Its now just updating the vault data struct, and forwarding any changes to the liquidation vault if required. This last part allows us to simplify the code dealing with the liquidation vault tokens. Threshold checks are now done in lib.rs.
Blocked by #16

refactor: vault token forwarding to liquidation vault

---

crates/btc-relay/src/lib.rs
crates/btc-relay/src/mock.rs
parachain/runtime/tests/mock/mod.rs
parachain/src/chain_spec.rs

refactor: remove relayer auth storage variables in btc-relay

---

crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/issue/src/types.rs
crates/redeem/src/default_weights.rs
crates/redeem/src/ext.rs
crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/redeem/src/types.rs
crates/refund/src/lib.rs
crates/sla/src/lib.rs
crates/staked-relayers/src/tests.rs
parachain/runtime/tests/mock/issue_testing_utils.rs
parachain/runtime/tests/mock/mod.rs
parachain/runtime/tests/mock/redeem_testing_utils.rs
parachain/runtime/tests/test_fee_pool.rs
parachain/runtime/tests/test_issue.rs
parachain/runtime/tests/test_redeem.rs
parachain/runtime/tests/test_vault_sla.rs

- (BREAKING) Changed IssueRequest struct
- (BREAKING) Changed RedeemRequest struct
- fixed cancel_redeem: 
- if reimburse=true: slash 130%, but give the polkabtc to the vault if it has capacity. Otherwise, it can now call `mint_tokens_for_reimbursed_redeem` after it locked additional collateral
- if reimburse = false, slash 30%
- refactored tests

Fix: cancel_redeem. Also, refactor: IssueRequest & RedeemRequest

---

crates/fee/src/lib.rs
crates/issue/src/benchmarking.rs
crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/issue/src/types.rs
parachain/runtime/tests/test_fee_pool.rs
parachain/runtime/tests/test_issue.rs
parachain/runtime/tests/test_vault_sla.rs

This changes request_issue such that the requested amount is equal to the amount of btc the user has to send. Note that this does mean that they will receive fewer PolkaBTC than they requested.
Changes are required in the UI. The testdata-gen tool needs to be updated as well, although it is not urgent - as far as I can see the current version has been broken for a long time, as it does not pay the fee

[BREAKING] fix(request_issue): make requested amount be the number of btc to be sent

---

crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/redeem/src/tests.rs
crates/staked-relayers/src/tests.rs
crates/vault-registry/src/default_weights.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/tests/test_issue.rs
parachain/runtime/tests/test_replace.rs

The breaking change here is the VaultStatus enum inside vault structs. The `Active` status is now `Active(bool)`, where `bool=true` indicates that the vault accepts new issues. This approach was taken of splitting it into two separate variants (e.g. `Active` and `Exiting`), because usually when we read the `status`, we don't need to differentiate between the two. The `get_active_vault` function that we use extensively would have to be turned into `get_active_or_exiting_vault` otherwise, which is just.. ugly. Not to mention that `exiting` is not 100% accurate.
Also note that unlike what Dom asked for, I did not include `BannedUntil` in the status enum. This is because of two reasons: first, after a temporary ban, you would be unable to return to the previous state, since we wouldn't …

[BREAKING] feat!: allow vaults to opt-out of new issues

---

crates/issue/src/benchmarking.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/redeem/src/benchmarking.rs
crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/refund/src/lib.rs
crates/refund/src/tests.rs
crates/replace/src/benchmarking.rs
crates/replace/src/lib.rs
crates/replace/src/tests.rs
crates/staked-relayers/src/benchmarking.rs
crates/staked-relayers/src/lib.rs
crates/staked-relayers/src/tests.rs
parachain/runtime/tests/mock/issue_testing_utils.rs
parachain/runtime/tests/mock/mod.rs
parachain/runtime/tests/mock/redeem_testing_utils.rs
parachain/runtime/tests/test_issue.rs
parachain/runtime/tests/test_redeem.rs
parachain/runtime/tests/test_replace.rs
parachain/runtime/tests/test_staked_relayers.rs

~~This fixes the issue, but I want to remove the tx_id argument altogether~~
Breaking changes:
- removed `tx_id` argument from execute issue/redeem/replace/refund & report_vault_theft

[BREAKING] Fix: tx_id validation

---

crates/redeem/src/mock.rs
crates/sla/src/lib.rs
crates/sla/src/mock.rs
crates/sla/src/tests.rs
crates/sla/src/types.rs
crates/staked-relayers/src/benchmarking.rs
crates/staked-relayers/src/default_weights.rs
crates/staked-relayers/src/ext.rs
crates/staked-relayers/src/lib.rs
crates/staked-relayers/src/mock.rs
crates/staked-relayers/src/tests.rs
crates/staked-relayers/src/types.rs
parachain/runtime/src/lib.rs
parachain/runtime/tests/mock/mod.rs
parachain/runtime/tests/test_fee_pool.rs
parachain/runtime/tests/test_staked_relayers.rs
parachain/src/chain_spec.rs

Breaking changes:
- remove many storage items from staked-relayers
- stake is now stored in `Stakes`
- removed many dispatchable functions 
- changed `RegisterStakedRelayer` event

[BREAKING] Refactor: remove voting

---

crates/bitcoin/src/types.rs
crates/btc-relay/src/benchmarking.rs
crates/btc-relay/src/lib.rs
crates/btc-relay/src/tests.rs
crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/redeem/src/ext.rs
crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/refund/src/ext.rs
crates/refund/src/lib.rs
crates/refund/src/tests.rs
crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/replace/src/tests.rs
crates/staked-relayers/src/lib.rs
crates/staked-relayers/src/tests.rs
parachain/runtime/tests/test_btc_relay.rs

Breaking change is that the arguments of `verify_and_validate_transaction` and `validate_transaction` changed. As far as I know, we don't use these functions ourselves though, in which case we don't need to make any changes in the clients/lib

[BREAKING] fix: correct txid calculation when there is witness data

---

crates/redeem/src/mock.rs
crates/sla/src/lib.rs
crates/sla/src/mock.rs
crates/sla/src/tests.rs
crates/sla/src/types.rs
crates/staked-relayers/src/benchmarking.rs
crates/staked-relayers/src/default_weights.rs
crates/staked-relayers/src/ext.rs
crates/staked-relayers/src/lib.rs
crates/staked-relayers/src/mock.rs
crates/staked-relayers/src/tests.rs
parachain/runtime/src/lib.rs
parachain/runtime/tests/mock/mod.rs
parachain/runtime/tests/test_btc_relay.rs
parachain/runtime/tests/test_fee_pool.rs
parachain/runtime/tests/test_staked_relayers.rs
parachain/src/chain_spec.rs

Remove the unnecessary storage fields and types from the staked-relayers pallet. Also removes the sla reward for duplicate block submission since there is no efficient way to prevent spamming.

refactor!: remove staked relayers registration

---

crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/redeem/src/types.rs
parachain/runtime/tests/test_redeem.rs

The breaking change here is the `CancelRedeem` event - its last field is now of type `RedeemRequestStatus`.
Non-breaking change: added MintTokensForReimbursedRedeem event

[BREAKING] Fix: redeem events

---

crates/currency/src/lib.rs
crates/nomination/src/default_weights.rs
crates/nomination/src/ext.rs
crates/nomination/src/lib.rs
crates/nomination/src/tests.rs
crates/nomination/src/types.rs
crates/redeem/src/ext.rs
crates/redeem/src/lib.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/slash.rs
parachain/runtime/Cargo.toml
parachain/runtime/tests/mock/mod.rs
parachain/runtime/tests/mock/nomination_testing_utils.rs
parachain/runtime/tests/test_issue.rs
parachain/runtime/tests/test_nomination.rs
parachain/runtime/tests/test_redeem.rs
parachain/runtime/tests/test_vault_registry.rs

At the moment, direct nominator withdrawals are made through the `request_collateral_withdrawal` dispatchable function.
Still need to implement/test the following:
- (implement) Liquidating vault for stealing minimizes nominator slashing
- (implement) Nominator reward distribution
- (implement) Vault withdrawal can force-refund nominators (related to reward distribution)
- (test) Non-operators cannot have collateral nominated
- (test) Nominations cannot exceed the max nomination ratio

Nomination withdrawal

---

.gitlab-ci.yml

chore: use CI_COMMIT_REF_NAME for tagging docker images

---

README.md
rust-toolchain.toml

This PR just suggests automating setup of the required toolchain for users and devs. We didn't discuss in our calls, but since this is as easy to suggest in a PR as it is in any other, form... :)
Feel free to close without comment if you'd rather not add this to your setup.
In our development, we have found that override files can help avoid time loss and productivity risks due to developer toolchains diverging after updates or users incorrectly following instructions.
Surfaced from @informalsystems' audit of interlay/btc-parachain at
e4cb057

Add rust-toolchain override file

---

crates/bitcoin/src/script.rs
crates/bitcoin/src/types.rs

Uses named constants for script length checks instead of magic numbers.
Aims to improve readability and reduce chance of discrepancy.
Discussed in meeting last week.
Surfaced from @informalsystems' audit of interlay/btc-parachain at
e4cb057

Replace magic numbers with named constants

---

crates/bitcoin/src/formatter.rs
crates/bitcoin/src/parser.rs
crates/bitcoin/src/types.rs
crates/btc-relay/src/tests.rs

Fixes [this report](https://www.notion.so/interlay/f207ebc861994e2988fcbd32895561f6?v=b4dc7a68fa584fabbabc646063b5d02e&p=982e022b44cc404aa11a58e6c491a1af)

fix: use an enum instead two separate options in Transaction

---

Cargo.toml

For the bug, see [the Rust blog](https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html). In short: incremental building sometimes resulted in a compiler crash, which would necessitate a `cargo clean` to recover.
When we upgrade compiler versions, we may be able to reenable incremental.

chore: disable incremental building to prevent triggering a compiler bug

---

crates/btc-relay/src/lib.rs
crates/btc-relay/src/tests.rs
crates/btc-relay/src/types.rs

The way `swap_main_blockchain` worked, was by traversing from the fork tip to the main chain by following the `prev_hash`es. It would move the blocks one by one to the main chain. When it reached the main chain, it moved all blocks that had a height higher than the first reached main block into the original fork. The problem is, it would move also the newly added blocks. As a result, blocks from the fork that overtakes main were unable to be used by transactions. 
With this PR, when a block is transferred to the main chain, the existing block is moved to into the fork. I also added some new invariants for `swap_main_blockchain`, basically checking that the blocks are moved correctly and agree with ChainsIndex metadata. My initial fix would simply swap the block of the main block chain …

[BREAKING] fix: do not remove newly added blocks from main in swap_main_blockchain 

---

crates/btc-relay/src/lib.rs
crates/btc-relay/src/tests.rs

`store_rich_header` was already called by `create_and_store_blockchain`, so we don't need to call it again

fix: remove duplicate block store in init

---

crates/bitcoin/examples/parse-transaction.rs
crates/bitcoin/src/formatter.rs
crates/bitcoin/src/parser.rs
crates/bitcoin/src/types.rs
crates/btc-relay/src/benchmarking.rs
crates/btc-relay/src/tests.rs
crates/issue/src/benchmarking.rs
crates/redeem/src/benchmarking.rs
crates/relay/src/benchmarking.rs
crates/relay/src/tests.rs
crates/replace/src/benchmarking.rs
parachain/runtime/tests/mock/mod.rs

- removed `flags` from transaction input - its value was not used, and can be deduced from the witness length, "If present, always 0001, and indicates the presence of witness data " ([source](https://en.bitcoin.it/wiki/Transaction))
- Added `TransactionInputSource` enum, to explicitly distinguish between coinbase and normal transactions. It cleans it up a little bit, although I had hoped to make `height` non-optional in coinbase transactions, but it turns out the inclusion depends on the transaction version
For ease of reviewing, I separated the functional changes from the changes to the tests

Refactor: transaction input

---

crates/bitcoin/src/error.rs
crates/bitcoin/src/parser.rs
crates/bitcoin/src/types.rs
crates/btc-relay/src/benchmarking.rs
crates/btc-relay/src/tests.rs
crates/issue/src/benchmarking.rs
crates/redeem/src/benchmarking.rs
crates/relay/src/benchmarking.rs
crates/replace/src/benchmarking.rs
standalone/runtime/tests/mock/mod.rs

According to [this spec change](https://github.com/interlay/interbtc-spec/pull/5)

fix: disallow bitcoin blocks with version < 4

---

crates/relay/src/lib.rs
crates/relay/src/tests.rs

See: https://spec.interlay.io/spec/relay.html#reportvaultdoublepayment

feat(relay): report double payment

---

Cargo.lock
crates/currency/Cargo.toml
crates/fee/Cargo.toml
crates/issue/Cargo.toml
crates/nomination/Cargo.toml
crates/redeem/Cargo.toml
crates/refund/Cargo.toml
crates/relay/Cargo.toml
crates/replace/Cargo.toml
crates/vault-registry/Cargo.toml
parachain/runtime/Cargo.toml
standalone/runtime/Cargo.toml

The rev that we depended on does not exist anymore. Probably I accidentally deleted it when I was having the `object not found - no match for id` problem. 
Now switching to `81511f1` from upstream, which is the latest master as of this writing.

fix: use upstream orml

---

crates/security/src/tests.rs

Based on the postconditions described [here](https://github.com/interlay/interbtc-spec/blob/master/interbtc-spec/docs/source/spec/security.rst)

test: spec-based postcondition tests of security module

---

crates/issue/src/ext.rs
crates/issue/src/tests.rs
crates/redeem/src/ext.rs
crates/relay/src/ext.rs
crates/relay/src/lib.rs
crates/relay/src/tests.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs

`Collateral<T>` and `Wrapped<T>` are type aliases to the `Balance` type (typically `u128`), there is no need for both to be specified on the `Vault` struct.

refactor!: merge duplicate numerical generics on vault struct

---

crates/redeem/src/tests.rs
standalone/runtime/tests/mock/redeem_testing_utils.rs
standalone/runtime/tests/test_redeem.rs

Several of these tests are adaptations of existing integration tests. To isolate the call and check for pre/post conditions, tests check the state of the parachain just before and after those calls. The existing tests were not removed, because they check broader correctness of chained calls.

chore(redeem): Complete spec-conformant tests

---

crates/exchange-rate-oracle/src/lib.rs
crates/exchange-rate-oracle/src/tests.rs
crates/redeem/src/benchmarking.rs
crates/redeem/src/lib.rs
crates/redeem/src/mock.rs
primitives/src/lib.rs
standalone/runtime/tests/mock/mod.rs

This is more of a discussion PR (but ready to merge if agreed); removes the unused Bitcoin fee rates `Half` and `Hour` since the redeem protocol only needs one input. I realize this will also need to be updated in the specification.

refactor!: remove unused Bitcoin fee estimates

---

Cargo.lock
crates/vault-registry/Cargo.toml
crates/vault-registry/src/ext.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
standalone/runtime/Cargo.toml
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/mock/reward_testing_utils.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_nomination.rs
standalone/runtime/tests/test_redeem.rs
standalone/runtime/tests/test_replace.rs
standalone/runtime/tests/test_staked_relayers.rs
standalone/runtime/tests/test_vault_registry.rs

- There is now a separate liquidation vault per currency. This fixes a problem where the amount of collateral associated with liquidated tokens was calculated incorrectly.
- ~~Added a `WrappedDebt` storage field that keeps track of the total number of wrapped tokens in all of the liquidation vaults. This is required to do `get_total_issued_tokens` without iteration.~~
- Introduced a new dependency on the `visibility` crate, which allows us to expose functions/types only when the `integration-tests` feature is enabled.
**BREAKING CHANGES**
- Storage
- `LiquidationVault` is now a map, indexed by currencyId
- Types
- `SystemVault` now has a `currencyId` field

fix!: use a separate liquidation vault for each currency

---

parachain/runtime/src/lib.rs
standalone/runtime/src/lib.rs

This change is required to be able to do runtime upgrades as sudo without fees. As I understand it, the cost of a transaction is `TransactionByteFee * number_of_bytes_in_extrinsic + weights.base_extrinsic + weight_of_function`. While `sudo_unchecked_weight` can set the last part to zero, we need the other parts to be zero as well. Eventually we will want to revert this change for better spam protection.
One thing to note is that subxt hangs when trying to execute a no-cost function, so we have to use polkadot.js.
Finally, I had to compile with `--release` in order to get this to work, otherwise the block production took too long. We have to make sure that the kusama node is fast enough to execute in the allowed block time.

fix: zero-cost base extrinsic weight, to be able to do runtime upgrade without fees

---

crates/btc-relay/src/lib.rs
crates/btc-relay/src/mock.rs
parachain/src/chain_spec.rs
standalone/runtime/tests/mock/mod.rs
standalone/src/chain_spec.rs

refactor: remove unused disable_op_return_check genesis config

---

parachain/runtime/src/lib.rs
standalone/runtime/src/lib.rs

[Apparently](https://github.com/paritytech/cumulus/issues/474) this macro is required for cumulus runtime upgrades

fix: use runtime_version attribute macro

---

crates/vault-registry/src/lib.rs
crates/vault-registry/src/mock.rs
crates/vault-registry/src/tests.rs

Register vault event is now `RegisterVault(T::AccountId, BalanceOf<T>, T::CurrencyId)`.

feat!: add currency id to register vault event

---

Cargo.lock
crates/btc-relay/Cargo.toml
crates/fee/Cargo.toml
crates/issue/Cargo.toml
crates/issue/src/mock.rs
crates/nomination/Cargo.toml
crates/nomination/src/mock.rs
crates/redeem/Cargo.toml
crates/redeem/src/mock.rs
crates/refund/Cargo.toml
crates/refund/src/mock.rs
crates/relay/Cargo.toml
crates/relay/src/mock.rs
crates/replace/Cargo.toml
crates/replace/src/mock.rs
crates/reward/Cargo.toml
crates/staking/Cargo.toml
crates/vault-registry/Cargo.toml
crates/vault-registry/README.md
crates/vault-registry/rpc/runtime-api/src/lib.rs
crates/vault-registry/rpc/src/lib.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/mock.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/Cargo.toml
parachain/runtime/src/lib.rs
standalone/runtime/Cargo.toml
standalone/runtime/src/lib.rs

This would have been a breaking change, but nobody depends in this code.
- removed `get_first_vault_with_sufficient_collateral` and `removed get_first_vault_with_sufficient_tokens`
- removed randomness pallet

chore: remove unused vault querying rpcs

---

crates/nomination/src/ext.rs
crates/nomination/src/lib.rs
crates/staking/src/lib.rs
crates/staking/src/mock.rs
crates/staking/src/tests.rs
crates/vault-registry/src/ext.rs
crates/vault-registry/src/lib.rs
standalone/runtime/tests/test_nomination.rs

- Storage fields related to stake are no longer indexed by the currency id
- The following events have changed:
- `DepositStake`
- `WithdrawStake`
- `ForceRefund`
- `IncreaseNonce`

refactor!: don't index stake by reward currency id

---

crates/refund/src/lib.rs
crates/refund/src/types.rs
crates/relay/src/lib.rs
primitives/src/lib.rs
standalone/runtime/tests/mock/issue_testing_utils.rs
standalone/runtime/tests/test_issue.rs

Removes `refund.amount_wrapped` in favour of `refund.amount_btc` (to harmonize with `redeem` and `replace`).
`amount_btc = total_amount_btc - fee_wrapped`

refactor!: remove amount_wrapped from refund struct

---

crates/fee/src/benchmarking.rs
crates/fee/src/lib.rs
crates/nomination/src/benchmarking.rs
crates/nomination/src/ext.rs
crates/nomination/src/lib.rs
crates/nomination/src/tests.rs
crates/staking/src/lib.rs
crates/staking/src/tests.rs
crates/vault-registry/src/ext.rs
standalone/runtime/tests/mock/nomination_testing_utils.rs
standalone/runtime/tests/test_fee_pool.rs
standalone/runtime/tests/test_nomination.rs

The previous implementation assumed that we could redistribute collateral as rewards which is not possible. To resolve this we now only withdraw and re-deposit the vault's collateral, nominators must provide the staking pool `T::Index` on `withdraw_collateral` and `withdraw_rewards`.

fix!: force refund can not re-distribute collateral

---

parachain/runtime/src/lib.rs

Fixes a bug where the downward transfer of KSM would be minted as DOT on the BTC-Parachain.

fix: use correct currency-id for relay chain currency

---

crates/escrow/src/lib.rs

fix: escrow docs should use an automatic link

---

crates/democracy/src/vote_threshold.rs

Since voting power decays, in rare cases the electorate can be less (even zero) than the sum of votes, leading to a divide-by-zero panic

fix: prevent divide-by-zero panic when electorate size is 0

---

parachain/runtime/kintsugi/src/lib.rs

`LaunchPeriod` is specified in the docs as 7 days. The voting period is not specified, but when it is 2 days, it could fall entirely in the weekend. This PR sets it to 7 days, [just like kusama](https://github.com/paritytech/polkadot/blob/289d9fc694dd60a331a1a8739c5fbe36c261d5a7/runtime/kusama/src/lib.rs#L560)

fix: set launch and voting period to 7 days

---

parachain/src/chain_spec.rs

The previous thresholds were set under the pessimistic assumption of 24 hours of network inactivity (non-liveness). This change balances out vault profitability with system safety assumptions. 
Network liveness guarantees are still on the safe side, since it is assumed that 6 Bitcoin block confirmations take 4 hours and only after that can a Burn Redeem be performed.

Lower collateral thresholds

---

parachain/runtime/kintsugi/src/lib.rs

chore: bump spec version to 6 for 1.5.0

---

crates/annuity/src/lib.rs
crates/annuity/src/mock.rs
crates/annuity/src/tests.rs
crates/supply/src/lib.rs
crates/vault-registry/src/lib.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/src/chain_spec.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_annuity.rs
standalone/src/chain_spec.rs

Prevents having to explicitly set these on Kintsugi, also no other project puts these account ids in storage.

refactor: compute pallet accounts at runtime

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_governance.rs

No need to whitelist Security calls when shutdown, since all allowed calls would be wrapped in sudo or democracy. Add test in standalone

chore: remove unnecessary Security whitelist entry when shutdown

---

parachain/runtime/kintsugi/src/lib.rs

chore: bump kintsugi spec version to 8 for 1.5.5

---

crates/escrow/src/lib.rs
crates/escrow/src/tests.rs

fix: restrict escrow minimum deposit to prevent vkint rounding to zero

---

Cargo.lock
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/Cargo.toml
parachain/runtime/testnet/src/lib.rs

We need to omrl-xcm pallet to be able to send messages to the relay chain that originate from the parachain's sovereign account. This is required for opening hrmp channels.
Also let PolkadotXcm pallet be in charge of deciding xcm versions (like acala)

feat: add orml-xcm pallet to send xcm message with sovereign account

---

standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_escrow.rs
standalone/runtime/tests/test_governance.rs

Adds an integration test to ensure that for a single user locking governance tokens, the `balance_at` and `total_supply` of vote currency is equal. Also checks the literal value of `total_supply` after a second user locks, to reuse in the JS implementation test.

test(standalone): Escrow

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs

- increase weight of xcm instructions. The current weight is very likely underestimated. This brings it inline with acala.
- Actually register a `ResponseHandler`, which (among other things) handles remote xcm version changes

Fix: xcm tweaks

---

Cargo.lock
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/Cargo.toml
parachain/runtime/testnet/src/lib.rs

I added the pallet to be able to execute functions on the relay chain with our sovereign account as origin, but it turns out the same can be achieved by calling the regular xcm's `send` function with `root` as origin.

chore!: remove orml-xcm

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs

Previously the xcm management functions were still allowed by the call filter, but because these are root-only functions, and sudo/governance ignores the filter, the whitelisting of these management functions was superfluous.

Chore: blacklist all xcm funcs

---

Cargo.lock

Polkadot 0.9.16 has finally been officially released - so far we used the preview, but this pr updates the dependency to the newest commit.

chore: upgrade to the release polkadot 0.9.16

---

docs/rococo-local-xcm.json
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs

Without this, assets can not be sent back to our chain. I did not apply the change to the interlay runtime - its xcm config is completely outdated, and I suggest we update it once 0.9.16 has landed on polkadot - it won't have to support older versions

fix: canonicalize asset used in xcm fee traders

---

Cargo.lock
parachain/runtime/testnet/Cargo.toml
parachain/runtime/testnet/src/lib.rs

Without this, we can't send tokens to the sibling chain in the rococo-local setup.

fix: allow unpaid xcm messages in the testnet runtime

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs
parachain/src/chain_spec.rs

Adding storage adds storage metadata, such that it is visible in the chain explorer. Adding the config sets a default xcm version, such that we don't have to sudo forceXcmVersion.
Addresses the finding of the HydraDX team

fix: add xcm storage and config in construct_runtime

---

crates/redeem/src/lib.rs

This prevents a griefing attack where users would redeem amounts just above the dust value: the vault would be losing tx fees for each redeem.

fix: don't charge a tx fee for execute_redeem

---

parachain/src/command.rs
parachain/src/service.rs

This doesn't fix the actual slot time on kintsugi, this is only an intermediate solution so that we can build nodes that will work for both kintsugi and testnets again. The slot time fix as described by Basti seems to be impossible - see element (there _is_ a way to fix it, but it involves stopping block production until the nodes are upgrade; this is the probably the best way forward in the long term)

fix: only use 6 second slot time for kintsugi

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs

As discussed on discord, we don't want the relay chain to be able to execute functions as root

fix: don't allow relay chain to execute as root

---

crates/democracy/src/lib.rs

See: https://github.com/paritytech/substrate/pull/10867

refactor: tidy democracy

---

Cargo.lock
crates/democracy/Cargo.toml
crates/democracy/src/lib.rs

Finding by [Security Research Labs](https://www.srlabs.de/).
This can be exploited by an attacker by sending a highly nested Proposal message.
Upon decoding, this will cause stack overflow.
An attacker can crafted highly nested message, for which, because of high amount of recursive calls, the stack size is insufficient during decoding. This can cause a panic in the runtime, which could potentially cause validators to fail at block production at miss their slots.
Consider using `DecodeLimit`

Stack overflow due to missing decode limit in do_enact_proposal

---

parachain/src/service.rs

The id in the [chainspec](https://github.com/interlay/interbtc/blob/master/parachain/res/kintsugi.json) is "kusama" rather than "kintsugi". We can change either the check in service, or the chainspec. I figured the risk of unforeseen consequences is smaller when going with the former approach, so that is what I did

fix: fix kintsugi node

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs
standalone/runtime/src/lib.rs

Example:
```rust
println!(
"{}",
sp_runtime::app_crypto::Ss58Codec::to_ss58check_with_version(
&sp_runtime::traits::AccountIdConversion::<primitives::AccountId>::into_account(&frame_support::PalletId(
*b"mod/fees"
)),
42_u16.into()
)
)
```

chore: document all system accounts

---

parachain/src/chain_spec.rs
standalone/src/chain_spec.rs

Opening this also for discussion since I'm not sure how to best parameterize this - what is clear however is that the previous input size is too low.

chore: increase expected redeem tx input size

---

crates/vault-registry/src/lib.rs
standalone/runtime/tests/test_redeem.rs

Users got confused because actions on liquidated vaults were returning `VaultNotFound`

refactor!: more explicit error when vault is liquidated

---

crates/democracy/src/lib.rs
crates/democracy/src/tests/public_proposals.rs

Currently there is no way for an author to remove a wayward proposal (and free up the deposit) without going again through governance. This re-purposes the `cancel_proposal` extrinsic to allow non-root users to remove their proposals. Note that no changes have been made to the external interface so it is not marked as a breaking change.

feat: re-purpose cancel_proposal for non-root

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_multisig.rs

[BREAKING] chore!: multisig pallet name should not be CamelCase

---

parachain/runtime/interlay/src/lib.rs

chore: vesting origin is kintsugi labs

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/interlay/src/xcm_config.rs

I copied the config from Kintsugi and made changes to use the other currencies. They are in separate commits, I recommend only looking at the second.
I wasn't sure what to use for the value of IntrPerSecond because we don't have an exchange rate for intr yet, so I left it unchanged with respect to the kintsugi value.
One other notable change compared to kintsugi is that I transfer the xcm fees to the block author rather than to treasury.
Also I removed the non-canonicalized trader items.

Fix: interlay xcm config

---

crates/issue/src/benchmarking.rs
crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/nomination/src/benchmarking.rs
crates/redeem/src/benchmarking.rs
crates/redeem/src/tests.rs
crates/refund/src/benchmarking.rs
crates/relay/src/benchmarking.rs
crates/relay/src/tests.rs
crates/replace/src/benchmarking.rs
crates/vault-registry/src/benchmarking.rs
crates/vault-registry/src/default_weights.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/mock/nomination_testing_utils.rs
standalone/runtime/tests/test_escrow.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_multisig.rs
standalone/runtime/tests/test_nomination.rs
standalone/runtime/tests/test_relayers.rs
standalone/runtime/tests/test_vault_registry.rs

With this change, the bitcoin public key is shared among all vaultids that share the same accountid.
Prior to calling `register_vault`, the vault _must_ call `update_public_key`, which sets the public key in the new `VaultBitcoinPublicKey` map.
A note to downstream: the `UpdatePublicKey` event type has changed, as well as the `register_vault` and `update_public_key` functions.
Note to reviewer: this PR is neatly split up into separate commits which may be useful in reviewing. Please also check the migration carefully.

[BREAKING] feat!: shared public key

---

parachain/runtime/interlay/src/constants.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/constants.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet/src/constants.rs
parachain/runtime/testnet/src/lib.rs

- [Kusama](https://github.com/paritytech/polkadot/blob/master/runtime/kusama/constants/src/lib.rs)
- [Polkadot](https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/constants/src/lib.rs)
- [Karura](https://github.com/AcalaNetwork/Acala/blob/master/runtime/karura/src/constants.rs)
- [Acala](https://github.com/AcalaNetwork/Acala/blob/master/runtime/acala/src/constants.rs)

refactor: move some time and currency consts into constants.rs

---

crates/issue/src/benchmarking.rs
crates/nomination/src/benchmarking.rs
crates/redeem/src/benchmarking.rs
crates/refund/src/benchmarking.rs
crates/relay/src/benchmarking.rs
crates/replace/src/benchmarking.rs
crates/vault-registry/src/benchmarking.rs
crates/vault-registry/src/default_weights.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_vault_registry.rs

Breaking because I renamed set_public_key -> register_public_key to reflect it's a one-time operation

[BREAKING] Fix!: disallow updating public key

---

crates/issue/src/benchmarking.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/replace/src/benchmarking.rs
crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/replace/src/tests.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/issue_testing_utils.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/mock/replace_testing_utils.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_nomination.rs
standalone/runtime/tests/test_redeem.rs
standalone/runtime/tests/test_relayers.rs
standalone/runtime/tests/test_replace.rs

This PR removes the griefing collateral parameters from `request_issue` and `request_replace` since we anyway override the value and it is complicated to determine ahead-of-time.

[BREAKING] refactor!: do not require griefing collateral argument

---

crates/vault-registry/Cargo.toml
crates/vault-registry/src/tests.rs
standalone/runtime/Cargo.toml
standalone/runtime/tests/test_btc_relay.rs

Allow opting out out of slow tests - this greatly speeds up tests locally. I chose to make it opt-out instead of opt-int so we can be sure that the CI includes everything. 
I  suggest setting up your vs code to use `cargo test --workspace --features skip-slow-tests --lib --bins --tests`. This skips 3 slow tests and skips doc-tests (which we do not use, but are slow to run even so). This runs in 13 seconds, compared to the 2m25s that `cargo test --workspace` takes.

chore: allow opt-out out of slow tests

---

crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_redeem.rs

Not accounting for CommittedTheft caused `decrease_issued` to take the wrong code path, which led to the execute_redeem call failing on vaults that were liquidated due to theft.
We have tests for redeem execution after liquidation, but all of them were on vaults that were liquidated because of undercollateralization rather than theft..

fix: allow redeem execution after theft

---

Cargo.lock
parachain/Cargo.toml
parachain/src/cli.rs
parachain/src/command.rs
parachain/src/service.rs
rpc/Cargo.toml
rpc/src/lib.rs
standalone/src/service.rs

This PR adds the `--instant-seal` option to the `interbtc-parachain` binary which automatically generates blocks when new transactions are added to the mempool or when calling the manual-seal RPC:
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "engine_createBlock", "params": [true, true, null]}' http://localhost:9933/
```
Succeeds #363

feat: add instant-seal for dev chain

---

crates/vault-registry/src/lib.rs
crates/vault-registry/src/types.rs
parachain/runtime/kintsugi/src/lib.rs

The liquidation vault currently has this:
```
toBeIssuedTokens: 0
issuedTokens: 6,354,070
toBeRedeemedTokens: 6,354,070
collateral: 30,544,076,056,403
```
This PR decrease `toBeRedeemedTokens` but not `issuedTokens`, so that afterwards people can liquidate_redeem. I confirmed that there is indeed an imbalance of `6,354,070` between the vault's issued tokens and the total issuance of kBTC. For future reference, this is how I checked:
```
const vaults = await api.query.vaultRegistry.vaults.entries();
console.log("vault total issued: ", vaults.map((v) => parseInt(v[1].unwrap().issuedTokens.toString())).reduce((a,b) => a+b));
// compare against tokens.totalIssuance
```
At current market value, the worth of the locked KSM is 129.8% of the KBTC, so for now that is ok, although the exchange rate …

fix: migration to fix invalid liquidation vault state

---

crates/bitcoin/src/parser.rs
crates/btc-relay/src/lib.rs
crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs

Note: I tried writing a test for this (specifically using a P2TR input) but it was decoded as P2WSH.

refactor: only refund issue if input address is valid

---

Cargo.lock
crates/staking/Cargo.toml
crates/staking/src/lib.rs
crates/staking/src/mock.rs
crates/staking/src/tests.rs
parachain/runtime/kintsugi/src/lib.rs

We had reports about people not receiving the rewards that they were expecting. The root cause for this was that vaults got slashed due to premium redeems, and there was a slashing-related bug in the staking code that caused vaults to receive too few rewards.

fix: correct rewards after slashing

---

crates/relay/src/benchmarking.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/test_relayers.rs

Fairly trivial change to liquidate at most 110% (or whatever the liquidation threshold is) on theft.
Note that because all holdings are liquidated on undercollateralization most existing tests do not break.

refactor: liquidate at most liquidation threshold on theft

---

crates/relay/src/lib.rs
crates/relay/src/tests.rs
standalone/runtime/tests/test_relayers.rs

Prevents vaults from transferring between registered addresses.

fix: disallow merge transactions

---

crates/vault-registry/src/types.rs
parachain/runtime/runtime-tests/src/relaychain/kusama_cross_chain_transfer.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_redeem.rs

The liquidation vault currently has 0 collateral, and with the upcoming migration it will have non-zero issued tokens but 0 to-be-redeemed. This checks that we allow kbtc to be burned without any collateral reward (i.e. there is no division by zero anywhere)

test: check that liquidation_redeem with 0 collateral works

---

parachain/src/chain_spec/mod.rs
parachain/src/chain_spec/testnet.rs

The bitcoin network property check that was recently added prevented vaults from running in the lib tests - it gave `Specified Bitcoin network differs from the one on the parachain: expected bitcoin-testnet, got regtest`

fix: specify regtest in local testnet properties

---

parachain/Cargo.toml
parachain/runtime/testnet/Cargo.toml
parachain/runtime/testnet/src/constants.rs
parachain/runtime/testnet/src/xcm_config.rs

The `dev-kintsugi` feature was enabled by default, and there was no easy way to disable it. Enabling `dev-interlay` would compile, but only due to [a compiler bug](https://github.com/rust-lang/rust/issues/97584). I also changed the tokens used in the xcm config

fix: remove dev-kintsugi feature

---

crates/bitcoin/src/address.rs
crates/issue/src/benchmarking.rs
crates/issue/src/tests.rs
crates/redeem/src/benchmarking.rs
crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/refund/src/benchmarking.rs
crates/refund/src/tests.rs
crates/relay/src/tests.rs
crates/replace/src/benchmarking.rs
crates/replace/src/tests.rs
crates/vault-registry/src/benchmarking.rs
parachain/runtime/testnet/src/xcm_config.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_redeem.rs

We saw a user lose bitcoin when he forgot to enter the address in the polkadotjs ui. This PR makes sure this can't happen again.

fix: disallow bitcoin hash of zero

---

crates/oracle/src/lib.rs
crates/oracle/src/tests.rs

This will help with getting the oracle list through Squid, removing the need for one more RPC call

feat!: Added oracle register/remove events to facilitate tracking through event indexers

---

parachain/runtime/interlay/src/lib.rs

- escrow.maxPeriod from 4,838,400 to 9676800
- democracy.minimumDeposit from 10,000,000,000 planck to 2,500,000,000,000 (250 vINTR required). That would allow about 7500 accounts to make a proposal if they stake their INTR for 2 years.

fix: update escrow period to double lease period, increase required vINTR for democracy and bump spec version

---

crates/replace/src/lib.rs
crates/replace/src/tests.rs

Removing this check further enables vault LPs to have someone else send extrinsics on their behalf.

feat: cancel_replace can be called by anyone

---

crates/staking/src/lib.rs
crates/staking/src/tests.rs
crates/vault-registry/src/ext.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/types.rs

In slash_stake, we reduce the vault's stake. That shouldn't cause them to lose rewards though, so we increase the rewards per token to compensate. However, the code contained a bug that caused the RewardsPerTokens to be only updated for KBTC, not for KINT. The fix is to iterate over both of these currencies

fix: iterate over all reward currencies in slash_stake

---

Cargo.lock
parachain/runtime/interlay/src/lib.rs
parachain/runtime/interlay/src/xcm_config.rs
parachain/runtime/runtime-tests/Cargo.toml
parachain/runtime/runtime-tests/src/lib.rs
parachain/runtime/runtime-tests/src/relaychain/kusama_cross_chain_transfer.rs
parachain/runtime/runtime-tests/src/relaychain/mod.rs
parachain/runtime/runtime-tests/src/relaychain/polkadot_cross_chain_transfer.rs
parachain/runtime/runtime-tests/src/relaychain/polkadot_test_net.rs

Some minor changes in interlay xcm that I'd like to deploy soon, and also xcm tests in preparation for opening the channels.
In the future I'd like to look into the possibility of merging kintsugi & interlay xcm tests, but I have a feeling that like the runtime config it would be very problematic

Test/fix: polkadot xcm

---

crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/vault-registry/src/benchmarking.rs
crates/vault-registry/src/default_weights.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_relayers.rs
standalone/runtime/tests/test_replace.rs
standalone/runtime/tests/test_vault_registry.rs

Implements https://github.com/interlay/interbtc/issues/637 without allowing recovery with outstanding wrapped tokens, to avoid [this](https://github.com/interlay/interbtc/issues/637#issuecomment-1155453172) edge case.

feat(vault): liquidation recovery

---

crates/annuity/src/mock.rs
crates/bitcoin/src/address.rs
parachain/runtime/runtime-tests/src/relaychain/kusama_cross_chain_transfer.rs
parachain/runtime/runtime-tests/src/relaychain/polkadot_cross_chain_transfer.rs
primitives/src/lib.rs

I didn't add a migration on the assumption that there are no assets registered just yet.

fix!: add coingecko id to asset metadata

---

crates/vault-registry/src/lib.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_vault_registry.rs

I stumbled upon this indirectly when I added some integrity checks. The actual fix is in `vault-registry/src/types.rs` - the `withdraw_replace_request` function would change the vault struct, but then the change got overwritten later on

fix: avoid overwriting changes in liquidate()

---

crates/issue/src/tests.rs
crates/redeem/src/benchmarking.rs
crates/redeem/src/tests.rs
crates/replace/src/benchmarking.rs
crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/replace/src/tests.rs
crates/vault-registry/src/benchmarking.rs
crates/vault-registry/src/default_weights.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_vault_registry.rs

With the removal of theft reporting, the wallet is no longer necessary.
Note: this will require the v4->v5 migration to run first. I tried leaving both in the code so they can be run back to back, but the `translate` function only allows you to put the current version, i.e. it does not allow you to put a VaultV5

chore!: remove wallet from vault struct

---

parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs

refactor!: testnet ss58s should be same as the primary runtimes

---

crates/currency/src/lib.rs
rust-toolchain.toml

This reverts commit a87b256efb4e361dda5e01f1dd67faa1f3742462.

Revert "chore: upgrade to nightly-2022-06-20"

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs

Since we force-deleted the tags due to the compiler mismatch, `spec_version` was incorrect.

chore: revert spec_version for 1.18.0

---

Cargo.lock
crates/escrow/rpc/Cargo.toml
crates/escrow/rpc/runtime-api/Cargo.toml
crates/escrow/rpc/runtime-api/src/lib.rs
crates/escrow/rpc/src/lib.rs
crates/escrow/src/lib.rs
crates/escrow/src/tests.rs
parachain/Cargo.toml
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/Cargo.toml
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/Cargo.toml
parachain/runtime/testnet-kintsugi/src/lib.rs
parachain/src/service.rs
rpc/Cargo.toml
rpc/src/lib.rs
standalone/runtime/Cargo.toml
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_escrow.rs

Adds RPCs for the escrow crate, to avoid functionality being re-implemented in the lib.

feat: Escrow RPCs

---

crates/annuity/src/lib.rs
crates/annuity/src/mock.rs
crates/reward/src/lib.rs
crates/vault-registry/src/ext.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/mock/issue_testing_utils.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/mock/redeem_testing_utils.rs
standalone/runtime/tests/mock/replace_testing_utils.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_replace.rs

This turned out to be a little bit more complicated that I anticipated. Before, we used a hook to set the reward-stake in increase/decrease_issued_tokens. With this change, we also have to update tokens when the `to_be_redeemed` tokens change. However, there are multiple operations that change both the issued and the to_be_redeemed tokens. With an added hook we'd have two stake updates for these. In some cases, like in execute redeem, we actually want 0 updates, since the change in to_be_redeemed tokens gets compensated by the change in issued tokens. So I refactored a little bit: the `vault-registry/lib.rs` file no longer has access to the raw increase/decrease token functions. Instead, it only uses the new `(request|cancel|execute)_(issue|redeem)_tokens` functions, which only update the …

fix: exclude toBeRedeemed tokens from generating rewards

---

crates/staking/src/lib.rs

I wrote this simplified implementation of the staking module in order to more clearly see what's going on in the module. I verified the accuracy by comparing it against the actual implementation in a large number of random simulations. I think it helps a lot in reasoning about the module behavior, for example in the context of migrations to fix past bugs.

doc: simplified model for the staking module

---

Cargo.lock
crates/collator-selection/Cargo.toml
crates/collator-selection/README.md
crates/collator-selection/src/benchmarking.rs
crates/collator-selection/src/lib.rs
crates/collator-selection/src/mock.rs
crates/collator-selection/src/tests.rs
crates/collator-selection/src/weights.rs
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/Cargo.toml
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/Cargo.toml
parachain/runtime/testnet-kintsugi/src/lib.rs

Forks [`pallet-collator-selection`](https://github.com/paritytech/cumulus/tree/polkadot-v0.9.24/pallets/collator-selection) and distinguishes `StakingCurrency` and `RewardsCurrency` so that we can use the illiquid `Escrow` balance for candidacy bonds. 
The reason for the split is because the `ReservableCurrency` implementation on the `Escrow` pallet is incompatible with the calls made in [`note_author`](https://github.com/paritytech/cumulus/blob/polkadot-v0.9.24/pallets/collator-selection/src/lib.rs#L473-L489).

feat: fork collator-selection and use escrow for bonding

---

Cargo.lock
crates/reward/rpc/Cargo.toml
crates/reward/rpc/runtime-api/Cargo.toml
crates/reward/rpc/runtime-api/src/lib.rs
crates/reward/rpc/src/lib.rs
parachain/Cargo.toml
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/Cargo.toml
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/Cargo.toml
parachain/runtime/testnet-kintsugi/src/lib.rs
parachain/src/service.rs
rpc/Cargo.toml
rpc/src/lib.rs
standalone/runtime/Cargo.toml
standalone/runtime/src/lib.rs

A few questions I'm blocked on at this point:
1. Build failure. This looks very similar to what I was getting when failing to implement the RPC in the runtimes, but here I've definitely added it to all four parachain runtimes and the standalone. Could you take a look please?
2. See comment below regarding possibly cleaning up the cast into Balance
3. We have two instances of the reward pallet, once using `VaultId` as the RewardId for vault block rewards, one using `AccountId` for escrow rewards. Right now I'm just trying to get the VaultId one to work for starters, as it's also going to be the main one useful for simplifying the lib, but I think it would be good to have both available as RPCs - how would I define that? The naive way of just adding a second impl to the runtimes doesn't …

Reward pallet RPC

---

crates/collator-selection/src/lib.rs
crates/collator-selection/src/tests.rs

Probably need to add some tests...

feat: kick collators without sufficient escrow balance

---

crates/redeem/src/benchmarking.rs
crates/redeem/src/default_weights.rs
crates/redeem/src/ext.rs
crates/redeem/src/lib.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/types.rs
standalone/runtime/tests/mock/redeem_testing_utils.rs
standalone/runtime/tests/test_redeem.rs

(User story copied from notion)
> ### User Story
> 
> As a Vault
> 
> I want to instantly redeem iBTC or kBTC
> 
> So that I 
> 
> 1. Can reuse my collateral atomically
> 2. Don’t have to send a BTC transaction to myself wasting BTC tx fees
> 3. And have the BTC in my wallet available right away (technically already the case since we don’t have theft reporting anymore)
> 
> ### Background
> 
> When vaults redeem with themselves, they basically burn iBTC, unlock BTC locked with them, and free collateral. This is a three step process at the moment:
> 
> - request_redeem schedules the redeem to be processed and gives the vault a BTC address from its own wallet to transfer BTC from its other addresses
> - the vault client listens for this request_redeem event and then sends the BTC to the …

[Breaking] feat: self-redeem

---

crates/issue/src/lib.rs
crates/issue/src/mock.rs
crates/issue/src/tests.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_issue.rs

Allows the `requester` to call `cancel_issue` up until expiry but the closer to the deadline this is done the more griefing collateral will be slashed.

feat: allow requester to call cancel_issue

---

parachain/runtime/kintsugi/src/lib.rs

See: https://voting.opensquare.io/space/kintsugi/proposal/QmQY4e1hjfVpioisSchaXYPr7iJddp7xaSkn74kEd8zNhc

feat: add migration to set the parameters for collator-selection

---

crates/nomination/src/benchmarking.rs
crates/nomination/src/default_weights.rs
crates/nomination/src/ext.rs
crates/nomination/src/lib.rs
crates/nomination/src/tests.rs
crates/vault-registry/src/lib.rs
standalone/runtime/tests/mock/nomination_testing_utils.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_nomination.rs

- now that we consider nomination to be fully trusted, we no longer need to enforce a nomination limit per vault for security reasons
- since the vault may still want to limit nominations for of economic reasons, we implement a configurable limit. It's just a configurable amount rather than a ratio, as discussed here https://discord.com/channels/745259537707040778/1028994764042944532/1029007960283815956

feat: configurable nomination limit

---

crates/nomination/src/default_weights.rs

fix: update new nomination default weights

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs

I found the following definition on the maximum block weight [here](https://substrate.stackexchange.com/questions/269/maximum-weight-in-a-block):
**Maximum Block Weight**
> The maximum block weight should be equivalent to one-third of the target block time, allocating one third for block construction, one third for network propagation, and one third for import and verification.
We can see that polkadot does allow for 2 seconds of compute time [here](https://github.com/paritytech/polkadot/blob/b984c40cc5217eda68f630e329320dc26578a0bc/runtime/common/src/lib.rs#L73-L74):
```
MAXIMUM_BLOCK_WEIGHT = WEIGHT_PER_SECOND * 2
```
However, it would seem most parachains (including statemine & statemint) are limited to 0.5 seconds of compute time …

chore: update max block weight comment

---

Cargo.lock
crates/currency/src/amount.rs
crates/loans/src/lend_token.rs
crates/loans/src/lib.rs
crates/loans/src/mock.rs
crates/loans/src/tests.rs
crates/loans/src/tests/interest_rate.rs
crates/loans/src/tests/liquidate_borrow.rs
crates/traits/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_loans.rs
standalone/runtime/tests/test_multisig.rs

Replaces the incorrect `get_price` integration with the conversion approach from the `currency` crate. The `PriceFeeder` associated type is replaced by `ReferenceAssetId`, which is the currency that prices are expressed in by the oracle. In our runtimes, that currency is `GetWrappedCurrencyId`. 
In some tests, `KINT` and `KBTC` are replaced with `INTR` and `IBTC`, because runtime currencies have been harmonized for these pairs: governance_currency / loan_reward_currency, and wrapped_currency / reference_currency.
Closes https://github.com/interlay/interbtc/issues/744

fix(loans): oracle integration

---

crates/collator-selection/Cargo.toml
crates/collator-selection/src/lib.rs
crates/collator-selection/src/mock.rs
crates/collator-selection/src/tests.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/src/service.rs

Implements the slot duration migration described [here](https://hackmd.io/@XuVYQ1rUQjGv8uRzzsdzuw/HkduIX4y5). Note that the service already has the necessary changes: https://github.com/interlay/interbtc/blob/63b485b2e8105eeaf20d960ed0a89443d2567d2a/parachain/src/service.rs#L474-L478

fix: add migration for kintsugi slot duration

---

.github/workflows/cargo-test.yml
Cargo.lock
crates/loans/src/lib.rs
parachain/Cargo.toml
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
parachain/src/chain_spec/mod.rs
parachain/src/chain_spec/testnet_interlay.rs
parachain/src/chain_spec/testnet_kintsugi.rs

Adds a migration to set the `min` and `max` exchange rates, if these are zero.
Closes https://github.com/interlay/interbtc/issues/791

fix(loans): Set min and max exchange rates on runtime upgrade

---

crates/currency/src/amount.rs
crates/currency/src/tests.rs
crates/currency/src/types.rs
crates/loans/src/interest.rs
crates/loans/src/lend_token.rs
crates/loans/src/lib.rs
crates/loans/src/mock.rs
crates/loans/src/rate_model.rs
crates/loans/src/tests.rs
crates/loans/src/types.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs

Replaces many uses of `FixedU128` with `Amount<T>`, based on this [feedback piece](https://github.com/interlay/interbtc/pull/785#discussion_r1029366161).
Since to an extent it completes https://github.com/interlay/interbtc/issues/751 I will close it with this PR, and leave the rest of the work for https://github.com/interlay/interbtc/issues/755.
Closes https://github.com/interlay/interbtc/issues/751

feat(loans): use Amount<T> instead of FixedU128

---

crates/loans/src/lib.rs
crates/loans/src/tests.rs
crates/loans/src/tests/liquidate_borrow.rs

Started out looking to add tests for the internal exchange rate based on https://github.com/interlay/interbtc/issues/747. I realised that `accrue_interest()` must always have been called before any of the following storage items is read: `TotalBorrows`, `TotalReserves`, `BorrowIndex`. This affects the value of the internal exchange rate, as well as other calculations.
- Decided against creating wrapper getters that auto-accrue interest, because that would make it even less obvious that many of the operations depend on `accrue_interest()` being called first. We will just have to be careful about this with future extensions.
- Improved comments on why `repay_all` uses `saturated_sub` instead of `checked_sub`.
- Included calls to `accrue_interest()` in the extrinsics that change the …

fix(loans): accrue interest before changing reserve balances

---

parachain/runtime/interlay/src/xcm_config.rs
parachain/runtime/kintsugi/src/xcm_config.rs

This is required for transfers of e.g. USDT back to statemine/t.

fix: set minimum xcm fee for statemine/t transfers

---

Cargo.lock
crates/democracy/Cargo.toml
crates/democracy/src/benchmarking.rs
crates/democracy/src/lib.rs
crates/democracy/src/tests.rs
crates/democracy/src/tests/public_proposals.rs
crates/democracy/src/tests/voting.rs
crates/loans/src/lib.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_governance.rs

Tables 2 proposals on week boundaries, i.e. monday morning at 9:00 UTC.
Implementation details: 
- stores the next boundary rather than recalculating it every block. This will be better performance-wise, and will make it easier for external tools to determine when tabling happens
- uses `chrono`
- after running the runtime upgrade, the `NextLaunchTimestamp` will be zero, meaning tabling will happen immediately
- Every time launching should happen, the next one is scheduled to be 7 days after the start of the current week. 
- We don't consider leap seconds since that kind of granularity is not required for us
- If block production stops for whatever reasons, and the week boundary is passed in the meantime, the next block will table the proposals regardless of the day
- Referendum duration …

feat: table two proposals on monday

---

primitives/Cargo.toml

fix: enable std on zenlink-protocol

---

Cargo.lock
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/lib.rs
parachain/src/chain_spec/interlay.rs
parachain/src/chain_spec/kintsugi.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_governance.rs

To facilitate Chopsticks testing - chopsticks will set overwrite the sudo key in the local fork. I added a migration that clears the key, which is required since the storage still contains the sudo key from back when we were still using sudo. I also added a test that verifies that when the key is unset, no sudo calls can be made.

feat: add a disabled sudo pallet back in

---

crates/loans/src/benchmarking.rs
crates/loans/src/farming.rs
crates/loans/src/interest.rs
crates/loans/src/lib.rs

Depends on https://github.com/interlay/interbtc/pull/821
Closes https://github.com/interlay/interbtc/issues/757
- Refactors lending events from tuple types to struct types
- Adds an `InterestAccrued` event emitted when a market is created and whenever interest is accrued, so event subscribes can track the latest internal exchange rate of lend tokens

Lending events refactoring

---

crates/issue/src/lib.rs
crates/issue/src/mock.rs
crates/issue/src/tests.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_issue.rs

Closes #822
Always transfer griefing collateral from an expired issue request to treasury instead of the Vault since it is likely under the capacity model that they may have deliberately blocked minting.

refactor: transfer expired griefing to treasury

---

crates/currency/src/lib.rs
crates/oracle/src/lib.rs
crates/oracle/src/tests.rs

Since we want to move toward having multiple oracle submitters, I think it's a good idea to have true medianizing rather than using the middle value. My reasoning is:
- the middle value was potentially unstable - given an input of even length, it would be very bad if we swap unpredictably between the two middle values
- with the true median, changes are a little bit smoother when the number of active oracles changes
- the number of authorized oracles is expected to be not very great, making the increased complexity of O(n*log(n)) (compared to O(n) for the middle value) not really important

feat: true oracle medianizing

---

crates/fee/src/lib.rs

The old rpc did not correctly take into account any commission. The new approach should be super robust: it just returns the difference in balances before and after doing a dry-run withdrawal.

fix: more robust vault reward calculation in rpc

---

crates/loans/src/farming.rs
crates/loans/src/lib.rs
crates/loans/src/tests.rs
crates/loans/src/tests/liquidate_borrow.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/tests/test_loans.rs

Investigating the dust amount edge case in lending (part of https://github.com/interlay/interbtc/issues/747) led to finding this dust whitelist. Dust amounts are currently set to zero but it's good to keep the whitelist up-to-date.
Adds lendining accounts to the dust whitelist on the testnets:
- `LoansAccount::get()` - Main account where pool assets are held, along with the interest rewards of the reserve.
- `Loans::incentive_reward_account_id()` - Reserve account where lending liquidation rewards are routed as Lend Tokens.
- `Loans::reward_account_id()` - Account where lending and borrowing subsidy rewards are deposited.
Two issues I am thinking of:
- The last two calls above require `unwrap`ping. If you believe this should be avoided I can look into some alternative implementations for …

feat(loans): add loans accounts dust whitelist on testnets

---

crates/loans/src/mock.rs
crates/loans/src/tests/liquidate_borrow.rs

Tests that if the liquidator of a bad loan chooses to be rewarded in a currency they already locked as collateral, the received amount is auto-locked as collateral as well.

test(loans): liquidation reward is auto-locked

---

parachain/src/command.rs

This [check](https://github.com/interlay/interbtc/blob/f1ed5205c29934170b0674e6b60a847028b9735e/parachain/src/command.rs#L132-L140) currently falls-through to the `testnet` runtime version since the id in the embedded `chain_spec` is "kusama".

fix: print correct runtime version

---

crates/reward/src/lib.rs
crates/reward/src/mock.rs
crates/reward/src/tests.rs

An oversight required for #826 to pay rewards in all currencies, otherwise we would get undefined results when distributing currencies that were not KINT/INTR or kBTC/iBTC. I have not updated the staking pallet since this is only required for farming rewards, Vaults are unaffected.
I wanted to simply iterate over the currencies in `RewardPerToken` but there was no way to do that just for the first key / prefix so the complexity for collecting and de-duplicating that list would be too great. Instead I have added a new storage value for all the reward currencies.
See also: https://github.com/paritytech/substrate/issues/13162

feat: allow rewards to be paid in any currency

---

Cargo.lock
crates/loans/Cargo.toml
crates/loans/src/interest.rs
standalone/runtime/Cargo.toml
standalone/runtime/tests/mock/loans_testing_utils.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_fee_pool.rs

Closes https://github.com/interlay/interbtc/issues/848
Adds a lend_token vault to the existing nomination rewards test, and also adds an integration test to check that accrued interest in lend_tokens is results in a higher stake of the lend_token currency in the Capacity pool.
FYI: Vaults will have their capacity model reward for Lend Tokens updated only when someone interacts with that market, but that should be often enough in practice.

feat(loans): update capacity model on exchange rate updates

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/test_fee_pool.rs

Without this, the rpc would fail with `Unable to estimate the current reward` because withdrawing the rewards would fail

fix: make rewards rpc work

---

crates/loans/src/benchmarking.rs
crates/loans/src/default_weights.rs
crates/loans/src/lib.rs
crates/loans/src/tests.rs

`withdraw_missing_reward` simply moves some incentive funds from the pallet account to an account that presumably didn't receive enough rewards. This can be done through a governance token transfer as well. If the `UpdateOrigin` is set to Root then it really makes no difference.

chore(loans): remove `withdraw_missing_reward` extrinsic

---

Cargo.lock
crates/loans/src/lib.rs
crates/loans/src/tests.rs
crates/loans/src/tests/lend_tokens.rs

Our lending implementation aims to forbid redeeming locked lend tokens. These must first be withdrawn, to simplify the logic. These checks were already there in the extrinsic functions (`redeem` and `redeem_all`), but there was a leftover check in `redeem_allowed` that still considered locked lend tokens OK to redeem. This fix is not critical because the redeem execution flow would never make it that far, but it's good to clean up.

fix(loans): remove logic that redeems locked lend tokens

---

crates/loans/src/types.rs

Embedding `Amount<T>` in an enum panics `cargo doc` with an unintelligible error (stemming from [here](https://github.com/rust-lang/rust/blob/6fc409ed0938cd2f501642abcaa675977fa5035a/src/librustc/traits/auto_trait.rs#L588), although that file no longer exists on the master branch of `rust`).
This PR just hides that enum from the docs.

fix(loans): cargo docs

---

crates/fee/src/lib.rs
parachain/runtime/common/src/lib.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_fee_pool.rs

The previous implementation did not work for lending tokens since it directly interfaced with the oracle pallet rather than using the `CurrencyConvert` converter that has additional logic for lending

fix: estimate vault reward rate for lend token vault collateral

---

crates/collator-selection/src/benchmarking.rs
crates/collator-selection/src/lib.rs

See: https://github.com/paritytech/cumulus/pull/1337
Also: https://github.com/paritytech/cumulus/pull/1714

refactor: bound entries in collator-selection

---

parachain/runtime/kintsugi/src/lib.rs

Oversight in the runtime configuration of Kintsugi which meant that `LastAuthoredBlock` was never updated when collators produced a block. Then because the `CollatorSelection` pallet was outdated it would incorrectly kick "stale" candidates.
Note: the additional rewards logic [here](https://github.com/interlay/interbtc/blob/6ad918a549bf1c1b3559c88fc5baf7dec85842a8/crates/collator-selection/src/lib.rs#L483) is superfluous because we already handle fees [here](https://github.com/interlay/interbtc/blob/6ad918a549bf1c1b3559c88fc5baf7dec85842a8/parachain/runtime/kintsugi/src/lib.rs#L348).

fix: kintsugi authorship config should use collator-selection hook

---

crates/staking/src/lib.rs
crates/staking/src/tests.rs

.. This doesn't really matter while nomination is disabled, since stakes will always be integers. If nomination is enabled, however, slashing can lead to non-integer stakes, so this becomes important. It's unsure what we'll do with the nomination, but this change doesn't hurt to have
Closes https://github.com/interlay/interbtc/issues/875

fix: use precise stake in reward calculation

---

crates/loans/src/benchmarking.rs
crates/loans/src/farming.rs
crates/loans/src/interest.rs
crates/loans/src/lend_token.rs
crates/loans/src/lib.rs
crates/loans/src/mock.rs
crates/loans/src/tests.rs
crates/loans/src/tests/edge_cases.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs

Closes https://github.com/interlay/interbtc/issues/864
Parameters are still named `asset_id`, although the type is now `CurrencyId`. Renaming would increase the size of the PR diff by quite a bit and I'm not sure how much it improves code readability.

Remove `Assets` config type from `Loans` pallet

---

crates/currency/src/amount.rs
crates/currency/src/lib.rs
crates/loans/Cargo.toml
crates/loans/src/farming.rs
crates/loans/src/interest.rs
crates/loans/src/lend_token.rs
crates/loans/src/lib.rs
crates/loans/src/mock.rs
crates/loans/src/tests.rs
crates/loans/src/tests/edge_cases.rs
crates/loans/src/tests/interest_rate.rs
crates/loans/src/tests/lend_tokens.rs
crates/loans/src/tests/liquidate_borrow.rs
crates/loans/src/types.rs
crates/traits/src/loans.rs
standalone/runtime/tests/test_loans.rs

~~This is WIP, there are still many functions that I'd want to convert to taking/returning `Amount`s, but I wanted to get feedback before I spend time doing that - I don't want to spend the time if you don't want to merge this with the audit going on. I think that once done, though, it'll result in~~ the code being more readable, more concise, and less error prone. It'll be clear what each balance indicates - there will be no more functions that take an underlying_id but the balance of a lend token, and there will be explicit failures when you try to e.g. add lending token amounts the underlying amounts. Plus code can use functions like `underlying.convert_to(lend_token_id)`, instead of querying the exchange rate and calling the correct conversion function

refactor: use Amounts consistently in loans pallet

---

crates/currency/src/amount.rs
crates/currency/src/tests.rs
crates/oracle/src/lib.rs

This math would first cast the `Amount` to fixedpoint, which would overflow easily on `Amount`s that had 18 decimals. This PR optimizes the casts away in `Oracle` and `Amount` multiplications and divisions

fix: avoid overflows in `Amount` math

---

standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/mock/redeem_testing_utils.rs
standalone/runtime/tests/mock/reward_testing_utils.rs
standalone/runtime/tests/test_fee_pool.rs
standalone/runtime/tests/test_redeem.rs

A bunch of changes to the tests that I made when investigating bugs related to nomination. The randomized tests are great at catching edge cases, but finding the root cause of failing tests can be a pain. To help with that, I refactored the randomized tests to output the actions that can then be re-imported to debug the problem.
I also changed the IdealRewardPool to keep intermediate results in fixedpoint numbers such that rounding errors don't accumulate as much. This was a bit of a problem when testing slashing.
The last addition is the inclusion of slashing in the randomized tests. This led to the discovery of https://github.com/interlay/interbtc/pull/847 , so it's disabled for now.

test: fee pool testing

---

crates/loans/src/interest.rs
crates/loans/src/lib.rs
crates/loans/src/tests/edge_cases.rs
crates/loans/src/tests/interest_rate.rs
crates/loans/src/types.rs

Found a better fix that initially planned for https://github.com/interlay/interbtc/issues/902, which also closes https://github.com/interlay/interbtc/issues/901.
- `accrued_interest` can be removed altogether by reusing the interest accrual function for total borrows. Using `saturating_sub` instead of `checked_sub` [here](https://github.com/interlay/interbtc/blob/ba7b2344503afdff6c003ebc03737309772d1990/crates/loans/src/lib.rs#L1533) is actually correct, because if `total_borrows` is always rounded up then it will exceed the sum of all debt owed by borrowers. This is undesirable because it would cause the internal exchange rate to be more generous to lenders than it should, because lend tokens could be redeemed for more cash than the protocol has (or will have after debt repayment). By …

fix(loans): Use compound interest formula

---

crates/dex-general/src/benchmarking.rs
crates/dex-general/src/fee/tests.rs
crates/dex-general/src/lib.rs
crates/dex-general/src/primitives.rs
crates/dex-general/src/swap/mod.rs
crates/dex-general/src/swap/tests.rs
crates/dex-swap-router/src/benchmarking.rs
crates/dex-swap-router/src/test.rs

This includes a few changes:
- removes `fee_point` upper bound and allows minting if zero
- increases granularity of `FEE_ADJUSTMENT` for minimum one basis point
- updates documentation to clarify protocol and swap fees
- adds `fee_rate` to `create_pair` call
See: https://github.com/zenlinkpro/Zenlink-DEX-Module/issues/62

[BREAKING] Refactor/dex general fees

---

crates/farming/src/benchmarking.rs
crates/farming/src/lib.rs
crates/farming/src/tests.rs

Since it is not possible to determine the exact number of LP tokens acquired when adding liquidity in order to bundle `Farming::deposit` we should reserve the entire "free" balance.

[BREAKING] refactor!: deposit all tokens in farming pallet

---

crates/farming/src/lib.rs
crates/reward/rpc/runtime-api/src/lib.rs
crates/reward/rpc/src/lib.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/Cargo.toml
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs

Also adds farming pallets to testnet-interlay runtime

feat: add rpc to estimate total farming rewards

---

Cargo.lock
crates/dex-stable/src/base_pool.rs
crates/dex-stable/src/base_pool_tests.rs
crates/dex-stable/src/lib.rs
crates/dex-stable/src/meta_pool_tests.rs

Errors occur here:
https://github.com/interlay/interbtc/blob/1f7533459a654d745002d1e519cf4fe9ecc4dfe2/crates/dex-stable/src/utils.rs#L41-L53
https://github.com/interlay/interbtc/blob/1f7533459a654d745002d1e519cf4fe9ecc4dfe2/crates/dex-stable/src/utils.rs#L90-L95
Same issue in Acala implementation: https://github.com/nutsfinance/stable-asset/blob/9a60645bc60e1c3452e8313de43179c4ba9b6e36/lib/stable-asset/src/lib.rs#L844
Related: https://github.com/saber-hq/stable-swap/blob/c621f5950e8071aaa595bc9ad674e970fccebdb2/stable-swap-math/src/curve.rs#L22

chore: prevent creating stable pool when a=0

---

crates/dex-general/src/lib.rs
crates/dex-general/src/swap/mod.rs

small refactoring to avoid array lookups. They were safe, but not immediately obviously so.

chore: avoid array indexing

---

crates/currency/src/amount.rs
crates/loans/src/lib.rs
crates/loans/src/tests.rs
crates/loans/src/tests/interest_rate.rs
crates/traits/src/loans.rs

This fixes an issue where I called `loans.redeem` with `1e8` as amount, but only `1e8 - 1` actually got released. This was due to the amount first being converted to the lend_token_id and then back to the underlying. The change is that we now only do one conversion: in `loans.redeem` we do only a single `to_lend_id`, while in `loans.redeem_all` we do only a single `to_underlying_id`.  
Closes #929

fix: release correct amount of underlying in loans.redeem

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
standalone/runtime/tests/test_governance.rs

The storage value is defined like this:
```
pub(super) type Key<T: Config> = StorageValue<_, T::AccountId, OptionQuery>;
```
The `OptionQuery` means that if you use the normal `get()` function, you get an Option. However, underlying storage is `T::AccountId` rather than `Option<T::AccountId>`. As such, the migration was incorrect - it put a value of incorrect length. It's not a huge deal since `get()` would still return `None` after failing to decode, but better to fix it properly.

fix: properly remove key in the sudo migration

---

parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs

Should be executed soon anyway

chore: remove kintsugi capacity migration

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs

For governance runtime upgrade

chore: bump spec versions to 1022000

---

crates/dex-swap-router/src/lib.rs
crates/dex-swap-router/src/mock.rs
crates/dex-swap-router/src/test.rs
parachain/runtime/kintsugi/src/dex.rs
parachain/runtime/testnet-interlay/src/dex.rs
parachain/runtime/testnet-kintsugi/src/dex.rs

Limits the route length in `swap_exact_token_for_tokens_through_stable_pool`. Longer term we might want to make the weight parametric over the route length. A slight complication is that to determine the number of swaps, you need to iterate over the `route` vector, so you'd be spending some computation prior to execution, which is not ideal. We could add an additional parameter containing the number of swaps to prevent that. But anyway for this fix will suffice  
Addresses https://github.com/interlay/srlabs-audit/issues/10

fix: limit amm swap route length

---

crates/loans/src/lib.rs

Remove lower bound check in add_market, and add upperbound check in update_market

fix: liquidate_incentive_reserved_factor bounds

---

crates/dex-general/src/fee/mock.rs
crates/dex-general/src/lib.rs
crates/dex-general/src/swap/mock.rs
crates/dex-swap-router/src/mock.rs
parachain/runtime/kintsugi/src/dex.rs
parachain/runtime/testnet-interlay/src/dex.rs
parachain/runtime/testnet-kintsugi/src/dex.rs

Quick fix so we can close https://github.com/interlay/srlabs-audit/issues/10. Longer term we should switch the boundedvec, but that will be a breaking change

fix: limit number of swaps in dexGeneral

---

Cargo.lock
crates/democracy/src/benchmarking.rs
crates/democracy/src/lib.rs
crates/democracy/src/tests.rs
crates/democracy/src/weights.rs
parachain/runtime/common/src/lib.rs
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/dex.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/runtime-tests/Cargo.toml
parachain/runtime/testnet-interlay/Cargo.toml
parachain/runtime/testnet-interlay/src/dex.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/Cargo.toml
parachain/runtime/testnet-kintsugi/src/dex.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
parachain/src/chain_spec/interlay.rs
parachain/src/chain_spec/kintsugi.rs
parachain/src/chain_spec/testnet_interlay.rs
parachain/src/chain_spec/testnet_kintsugi.rs
standalone/runtime/Cargo.toml
standalone/runtime/src/lib.rs
standalone/runtime/tests/test_governance.rs
standalone/src/chain_spec.rs

Addresses https://github.com/interlay/interbtc/issues/889
While refactoring, I ran into this:  https://github.com/interlay/interbtc/blob/1a1afa90228f37c9ade4acbda8275c2f5cfe85ce/crates/democracy/src/lib.rs#L1033
There are a couple of problems with this:
- The Slash hook was incorrect - it would have minted KINT when vKINT got burned (in a 1:1 ratio)
- The Slash hook was anyway never called with a non-zero amount due to slash_reserved being a noop, always returning zero: https://github.com/interlay/interbtc/blob/1a1afa90228f37c9ade4acbda8275c2f5cfe85ce/crates/escrow/src/lib.rs#L696
- So, effectively, no slashing ever takes place in the democracy pallet. Failed proposals lead to vkint staying locked forever
As discussed on discord, we now  just unreserve vkint for failed proposals.

refactor!: simplify treasury

---

crates/farming/src/mock.rs
crates/fee/src/mock.rs
crates/issue/src/mock.rs
crates/nomination/src/mock.rs
crates/redeem/src/mock.rs
crates/replace/src/mock.rs
crates/reward/src/lib.rs
crates/reward/src/migration.rs
crates/reward/src/mock.rs
crates/vault-registry/src/mock.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs

Prevents this from endlessly growing, in benchmarking we should consider the max for the worst-case.

refactor: bound reward currencies

---

crates/democracy/src/lib.rs

So OpenSquare can update when proposals are cancelled

[BREAKING] feat!: add separate event for cancelled proposal

---

crates/dex-general/src/fee/mock.rs
crates/dex-general/src/lib.rs
crates/dex-general/src/swap/mock.rs
crates/dex-swap-router/src/mock.rs
parachain/runtime/kintsugi/src/dex.rs
parachain/runtime/testnet-interlay/src/dex.rs
parachain/runtime/testnet-kintsugi/src/dex.rs

- Replaces usage of `BTreeMap` with `BoundedBTreeMap`
- Adds `MaxBootstrapRewards` and `MaxBootstrapLimits` config items as map upper bounds, and sets each to `1000` in the runtimes

feat(dex-general): use BoundedBTreeMap

---

crates/bitcoin/src/formatter.rs
crates/bitcoin/src/merkle.rs
crates/bitcoin/src/parser.rs
crates/bitcoin/src/script.rs
crates/bitcoin/src/types.rs
crates/btc-relay/src/benchmarking.rs
crates/btc-relay/src/lib.rs
crates/btc-relay/src/tests.rs
crates/issue/src/benchmarking.rs
crates/issue/src/ext.rs
crates/issue/src/lib.rs
crates/issue/src/tests.rs
crates/redeem/src/benchmarking.rs
crates/redeem/src/ext.rs
crates/redeem/src/lib.rs
crates/redeem/src/tests.rs
crates/replace/src/benchmarking.rs
crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/replace/src/tests.rs
standalone/runtime/tests/bitcoin_data.rs
standalone/runtime/tests/mock/issue_testing_utils.rs
standalone/runtime/tests/mock/mod.rs
standalone/runtime/tests/mock/redeem_testing_utils.rs
standalone/runtime/tests/test_btc_relay.rs
standalone/runtime/tests/test_issue.rs
standalone/runtime/tests/test_redeem.rs
standalone/runtime/tests/test_replace.rs

Closes https://github.com/interlay/interbtc/issues/605
Open points:
- Should we remove the `hash` field from `BlockHeader`?
- Should we use `BoundedVec` for the scripts and witnesses?

refactor!: remove all Bitcoin parsing and use concrete types

---

crates/loans/src/lib.rs
crates/loans/src/migration.rs
crates/loans/src/mock.rs
crates/loans/src/tests.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs

- Migrates inconsistent lend-token storage (both `free` and `reserved`) if any is found, by manually calling `lock_if_account_deposited(...)` (what the missing hooks were supposed to do)
- Sets orml-token hooks for `loans` in the Kintsugi runtime ~~(I assume this only fixes for a new genesis though - how do I set the config of a live runtime?)~~
- Bumps Kintsugi spec from `1023002` to `1023003`
- Adds TODO for setting the orml-tokens hooks before the interlay launch. Maybe easier to track as a GitHub issue in the Interlay DeFi Hub milestone?
- Tested using `try-runtime` on Kintsugi mainnet (`RUST_LOG=info target/release/interbtc-parachain try-runtime --wasm-execution=compiled --chain=kintsugi-latest --runtime target/release/wbuild/kintsugi-runtime-parachain/kintsugi_runtime_parachain.wasm …

Loans toggle migration

---

crates/dex-general/src/lib.rs
crates/dex-stable/src/base_pool.rs
crates/dex-stable/src/base_pool_tests.rs
crates/dex-stable/src/lib.rs
crates/dex-stable/src/meta_pool.rs
crates/dex-stable/src/meta_pool_tests.rs
crates/dex-stable/src/mock.rs
crates/dex-stable/src/primitives.rs
crates/dex-stable/src/rpc.rs
crates/dex-stable/src/utils.rs
crates/dex-swap-router/src/mock.rs
parachain/runtime/kintsugi/src/dex.rs
parachain/runtime/testnet-interlay/src/dex.rs
parachain/runtime/testnet-kintsugi/src/dex.rs

So we can remove `without_storage_info` annotation

chore: bound number of pool currencies in dex-stable

---

crates/democracy/src/benchmarking.rs
crates/tx-pause/src/benchmarking.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs

Tested all `interlay` and `kintsugi` benchmarks, `democracy` and `orml-vesting` were the only failures

chore: fix remaining benchmarks

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/testnet-interlay/src/lib.rs
parachain/runtime/testnet-kintsugi/src/lib.rs
standalone/runtime/src/lib.rs

I still need to investigate the consequences of this change, but I believe we are currently undercharging on most operations due to the `DbWeight` being set to `Default::default()`.

fix: use RocksDbWeight for DbWeight

---

Cargo.lock
parachain/runtime/common/src/lib.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/runtime-tests/Cargo.toml
parachain/runtime/runtime-tests/src/parachain/escrow.rs
parachain/runtime/runtime-tests/src/utils.rs

Related: https://github.com/interlay/interbtc/issues/843

refactor: deduplicate escrow reward rate runtime-api and add sanity test

---

Cargo.lock
primitives/Cargo.toml
primitives/src/lib.rs

The Pr adds the following things,

feat: add scale encode and decode as traits to CurrencyId.

---

crates/escrow/rpc/runtime-api/src/lib.rs
crates/escrow/rpc/src/lib.rs
crates/escrow/src/lib.rs
crates/escrow/src/tests.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs

Closes https://github.com/interlay/interbtc/issues/1127

chore: add rpc to get free stakable funds

---

crates/bitcoin/src/types.rs

CI is currently failing with this error
```
error: this URL is not a hyperlink
Error:   --> crates/bitcoin/src/types.rs:28:9
|
28 | /// See https://bitslog.com/2018/06/09/leaf-node-weakness-in-bitcoin-merkle-tree-design/ .
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://bitslog.com/2018/06/09/leaf-node-weakness-in-bitcoin-merkle-tree-design/>`
```

chore: fix docs building error

---

crates/nomination/Cargo.toml
crates/nomination/src/benchmarking.rs
crates/nomination/src/ext.rs
crates/nomination/src/lib.rs
crates/nomination/src/tests.rs
crates/replace/src/ext.rs
crates/replace/src/lib.rs
crates/reward/src/lib.rs
crates/staking/src/lib.rs
crates/vault-registry/src/ext.rs
crates/vault-registry/src/lib.rs
crates/vault-registry/src/pool_manager.rs
crates/vault-registry/src/tests.rs
crates/vault-registry/src/types.rs
parachain/runtime/runtime-tests/src/parachain/issue.rs
parachain/runtime/runtime-tests/src/parachain/nomination.rs
parachain/runtime/runtime-tests/src/parachain/vault_registry.rs
parachain/runtime/runtime-tests/src/utils/nomination_utils.rs

Hacky fix to allow Vaults to withdraw all collateral since #974 unintentionally introduced a bug that prevents this. Specifically, due to a loss in precision the calculation in `withdraw_stake` (`apply_slash`) may produce a smaller amount than `TotalCurrentStake` which results in the `InsufficientFunds` error.

[BREAKING] fix: allow vault to withdraw all collateral

---

crates/supply/src/benchmarking.rs
crates/supply/src/lib.rs
crates/supply/src/mock.rs
crates/supply/src/tests.rs

As reported by SRLabs:
The conversion of `total_supply` to `FixedPointNumber` exceeds accuracy and returns None, which crashes the blockchain once `unwrap()` is called.
The [begin_block](https://github.com/interlay/interbtc/blob/76deccd239191d89812ea4db566be5776e56359d/crates/supply/src/lib.rs#L166) function from pallet **supply** will increase the Currency total_issuance based on the inflation rate, using [deposit_creating](https://github.com/interlay/interbtc/blob/76deccd239191d89812ea4db566be5776e56359d/crates/supply/src/lib.rs#L181).
Because total_supply can become too large, [checked_from_integer](https://github.com/interlay/interbtc/blob/76deccd239191d89812ea4db566be5776e56359d/crates/supply/src/lib.rs#L173) will return None and the a panic is being raised because of the …

fix: unsafe usage of unwrap in supply

---

Cargo.lock
Cargo.toml
parachain/Cargo.toml
parachain/runtime/common/Cargo.toml
parachain/runtime/common/src/evm/mod.rs
parachain/runtime/common/src/evm/precompiles.rs
parachain/runtime/common/src/lib.rs
parachain/runtime/interlay/Cargo.toml
parachain/runtime/interlay/src/evm.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/Cargo.toml
parachain/runtime/kintsugi/src/evm.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/runtime/runtime-tests/Cargo.toml
parachain/runtime/runtime-tests/src/parachain.rs
parachain/runtime/runtime-tests/src/parachain/ethereum.rs
parachain/src/chain_spec/interlay.rs
parachain/src/chain_spec/kintsugi.rs
parachain/src/chain_spec/mod.rs
parachain/src/chain_spec/testnet_interlay.rs
parachain/src/chain_spec/testnet_kintsugi.rs
parachain/src/cli.rs
parachain/src/command.rs
parachain/src/eth.rs
parachain/src/lib.rs
parachain/src/main.rs
parachain/src/service.rs
rpc/Cargo.toml
rpc/src/eth.rs
rpc/src/lib.rs

Closes https://github.com/interlay/interbtc/issues/1098
Adds the following pallets to the `interlay` and `kintsugi` runtimes in addition to those required for RPC compatibility.
Controls the price per gas unit, updates based on the weight of the previous block - decreases if below or increases if above the target.
Emulation for block processing, validates and stores (EVM) transactions then constructs the Ethereum compatible block `on_finalize`.
Contains the `SputnikVM` to execute EVM bytecode compatible with the Ethereum mainnet.
- Account version uses [`HashedAddressMapping`](https://github.com/paritytech/frontier/blob/1a718546085be20ce381b70e1f9e4c8b4d4b1f03/frame/evm/src/lib.rs#L715)
> All non-root calls are disabled.
Stores the chain ID which is used by the EVM runner.

feat: add frontier evm

---

Cargo.lock
crates/democracy/Cargo.toml
crates/democracy/src/lib.rs
crates/democracy/src/tests.rs
parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs

Closes https://github.com/interlay/interbtc/issues/950

refactor: simplify launch timestamp logic

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs

closes https://github.com/interlay/interbtc/issues/1143

feat: allow polkadotXcm.send

---

.github/workflows/notify-breaking.yml

Replace the outdated `Ilshidur/action-discord@master` github action for sending Discord notifications with a simple curl command.

chore: update discord notifications

---

.github/workflows/benchmark.yml

This change resolve the parsing for commands containing non-alphanumerical characters (`-`)

chore: update benchmark command parsing

---

.github/workflows/benchmark.yml

fix: escape ts benchmark syntax

---

parachain/runtime/kintsugi/src/contracts.rs
parachain/src/service.rs

Making this PR to run the benchmarks for the release, no functional changes are included.

chore: cleanup unused and deprecated code

---

.github/workflows/benchmark.yml

Benchmark automation should finally be working now (tested on a private fork). The "Update comment" step will fail when running the benchmarks for the whole runtime because the output is too big but I have kept it since it should work for individual pallets.

chore: commit new weights manually

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs
parachain/src/eth.rs
parachain/src/service.rs

Caused the testnet deployment to fail because it was trying to use the 6s slot duration configured for old kintsugi mainnet imports.
Also ran into [this issue](https://github.com/paritytech/frontier/issues/603) when trying to sync, solved by removing the `FrontierBlockImport` wrapper.

fix: only adjust kintsugi mainnet slot duration

---

.github/workflows/benchmark.yml

The output of the benchmark script can be too long - more than the allowed 65536 characters for a github PR comment.
This change will trim the output so it can be accepted by the Github PR API. The full output remains available in the github action run log.

chore: update benchmark workflow to trim too long output

---

parachain/runtime/interlay/src/lib.rs
parachain/runtime/kintsugi/src/lib.rs

Otherwise `NextLaunchTimestamp` will be set really far in the future

fix: launch period should be seconds

---

crates/redeem/src/lib.rs
parachain/runtime/runtime-tests/src/parachain/redeem.rs

On `cancel_redeem` we have two branches:
- **Retry**: Vault loses 10% collateral
- **Reimburse**: Vault loses 110% collateral, to get it back to 10% effective loss they get to have the equivalent of 100% in KBTC
Unfortunately this doesn't account for the case when the Vault is liquidated, which on reimburse would still send them the "to-be-burned" KBTC. However because the Vault is already liquidated there is insufficient collateral to back these tokens, they should be burned and the accounting on the liquidation vault should be updated to reflect the decreased issued tokens.

fix: don't mint kbtc in cancel_redeem for liquidated vault

---

crates/loans/src/rate_model.rs
crates/loans/src/tests/market.rs

Recently all USDT on Polkadot was borrowed, leading to Moonwell USDT borrow rates of 192% and Interlay $492k of USDT max borrowed, resulting in Interlay USDT borrow rate pegged at 45-50%. The negative thing was that there was no remaining USDT lending liquidity for lenders to withdraw their capital.
Interlay referenda 96 was approved to adjust the USDT/USDC lending params to set the jump rate to 20% and the full rate to 150% with optimal utilization of 80%. After community and team discussion, this solution was agreed to use the higher full rate to push lending back down towards the optimal lending utilization.
https://interlay.subsquare.io/democracy/referenda/96
Unfortunately the referenda failed to execute because the 150% proposed full rate exceeded the hard-coded max value of 50% for …

fix(rate_model): increase MAX jump rate and full rate
