interlay/interbtc

parachain/runtime/src/lib.rs
=> fix: convert trait required by cumulus-polkadot

crates/vault-registry/src/tests.rs, crates/vault-registry/src/types.rs, parachain/runtime/tests/mock.rs, parachain/runtime/tests/test_issue.rs, parachain/runtime/tests/test_redeem.rs, parachain/runtime/tests/test_replace.rs
=> fix: limit the amount of collateral slashed in liquidate() based on secure threshold

crates/btc-relay/README.md, crates/btc-relay/src/lib.rs, crates/btc-relay/src/mock.rs, crates/btc-relay/src/tests.rs, crates/issue/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/replace/src/mock.rs, crates/staked-relayers/src/mock.rs, parachain/runtime/src/lib.rs, parachain/runtime/tests/mock.rs, parachain/runtime/tests/test_btc_relay.rs
=> feat: add block submitter to relay events

crates/sla/src/lib.rs
=> feat: add delta_sla to update sla events

crates/btc-relay/src/ext.rs, crates/btc-relay/src/lib.rs, crates/btc-relay/src/tests.rs, crates/security/src/lib.rs, crates/security/src/tests.rs, crates/staked-relayers/src/ext.rs, crates/staked-relayers/src/lib.rs, parachain/runtime/src/lib.rs, parachain/runtime/tests/test_issue.rs, parachain/runtime/tests/test_redeem.rs, parachain/runtime/tests/test_replace.rs
=> feat: add sudo functionality on security and btc-relay

Cargo.lock, crates/bitcoin/Cargo.toml, crates/bitcoin/src/script.rs, crates/bitcoin/src/types.rs, crates/btc-relay/src/lib.rs, crates/parachain-tokens/src/types.rs, parachain/runtime/src/lib.rs, parachain/service/src/cumulus.rs, parachain/service/src/grandpa.rs, parachain/src/chain_spec.rs
=> chore: upgrade rococo-v1 dependencies

parachain/runtime/src/lib.rs
=> chore: bump spec version for 0.5.5

crates/btc-relay/src/ext.rs, crates/btc-relay/src/lib.rs, crates/exchange-rate-oracle/src/ext.rs, crates/exchange-rate-oracle/src/lib.rs, crates/exchange-rate-oracle/src/tests.rs, crates/security/src/lib.rs, crates/security/src/tests.rs
=> feat: automatic oracle offline reporting on_initialize

crates/bitcoin/src/types.rs, crates/btc-relay/src/lib.rs, crates/btc-relay/src/tests.rs, crates/redeem/src/mock.rs, crates/sla/src/lib.rs, crates/sla/src/mock.rs, crates/sla/src/types.rs, crates/staked-relayers/src/benchmarking.rs, parachain/runtime/tests/mock/mod.rs, parachain/src/chain_spec.rs
=> feat: update relayer sla on duplicate block

Cargo.lock, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs
=> feat(aggregator): added utility pallet

crates/vault-registry/src/lib.rs, crates/vault-registry/src/types.rs
=> feat: add sudo call to register vault with id

crates/staked-relayers/src/lib.rs
=> refactor!: remove store_block_headers in favour of utility::batch

Jenkinsfile
- Clean-up old artifacts to avoid running out of disk space
- Push build notifications to Discord
- Push github draft release for all tagged builds
=> Chore: fix automated github release

crates/bitcoin/src/address.rs, crates/bitcoin/src/error.rs, crates/bitcoin/src/formatter.rs, crates/bitcoin/src/merkle.rs, crates/bitcoin/src/parser.rs, crates/bitcoin/src/types.rs, crates/btc-relay/src/lib.rs
=> chore: run cargo clippy and fix all warnings on bitcoin crate

README.md
=> chore: add build dependencies to README

parachain/README.md
=> chore: add tarpaulin command to parachain/README.md

crates/bitcoin/src/parser.rs, crates/btc-relay/src/lib.rs, crates/btc-relay/src/tests.rs
=> fix: reject transactions with duplicate recipients

crates/btc-relay/src/lib.rs, crates/issue/src/benchmarking.rs, crates/issue/src/ext.rs, crates/issue/src/lib.rs, crates/issue/src/mock.rs, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/test_btc_relay.rs, parachain/runtime/tests/test_issue.rs, parachain/runtime/tests/test_staked_relayers.rs
[This](https://www.notion.so/interlay/ecfe090112974b3fad9a668f50a2fa87?v=3c4504666fa84e4990f50c2df708303f&p=95fbb2d2e2aa40e6a125dc68ff8a2c17) ticket
=> fix: don't allow issues while btc-relay is initializing

parachain/runtime/tests/test_oracle.rs
Forgot to add this file in #80
=> test: oracle when parachain is shutdown

crates/fee/src/lib.rs, crates/issue/src/lib.rs, crates/parachain-tokens/src/lib.rs, crates/redeem/src/lib.rs, crates/replace/src/lib.rs, crates/staked-relayers/src/lib.rs, crates/vault-registry/src/lib.rs
=> feat: dispatchable amounts should be compact

crates/btc-relay/src/mock.rs, crates/exchange-rate-oracle/src/mock.rs, crates/fee/src/mock.rs, crates/issue/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/replace/src/mock.rs, crates/security/src/lib.rs, crates/security/src/mock.rs, crates/security/src/tests.rs, crates/sla/src/mock.rs, crates/staked-relayers/src/mock.rs, crates/vault-registry/src/mock.rs, parachain/runtime/src/lib.rs
=> refactor: convert security pallet to FRAME v2

crates/replace/src/lib.rs
=> refactor!: withdraw_replace amount should be compact

crates/btc-relay/src/mock.rs, crates/fee/src/benchmarking.rs, crates/fee/src/ext.rs, crates/fee/src/lib.rs, crates/fee/src/mock.rs, crates/fee/src/tests.rs, crates/fee/src/types.rs, crates/issue/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/replace/src/mock.rs, crates/sla/src/mock.rs, crates/staked-relayers/src/mock.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, crates/vault-registry/src/types.rs, parachain/runtime/src/lib.rs, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/test_staked_relayers.rs, parachain/src/chain_spec.rs
=> refactor: derive sovereign account for modules

crates/collateral/src/lib.rs, crates/collateral/src/tests.rs, parachain/runtime/src/lib.rs
=> refactor: convert collateral pallet to FRAME v2

crates/treasury/src/lib.rs, crates/treasury/src/tests.rs, parachain/runtime/src/lib.rs
=> refactor: convert treasury pallet to FRAME v2

crates/bitcoin/src/address.rs, crates/bitcoin/src/formatter.rs, crates/bitcoin/src/parser.rs, crates/bitcoin/src/script.rs, crates/bitcoin/src/types.rs
=> feat: extract p2wsh addresses

Cargo.lock, crates/bitcoin/src/utils.rs, crates/redeem/src/ext.rs, crates/redeem/src/lib.rs, crates/redeem/src/mock.rs, crates/redeem/src/tests.rs, crates/redeem/src/types.rs, crates/staked-relayers/src/tests.rs, parachain/Cargo.toml, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/mock/redeem_testing_utils.rs, parachain/runtime/tests/test_redeem.rs, parachain/runtime/tests/test_vault_sla.rs, parachain/src/chain_spec.rs
Breaking changes:
- transfer_fee_btc in the RedeemRequest struct
- RequestRedeem event now includes transfer_fee_btc
=> [BREAKING] fix: redeem transfer fee

README.md, docs/rococo.md
=> chore: update readme to point to github

crates/btc-relay/src/lib.rs, crates/exchange-rate-oracle/src/lib.rs, crates/fee/src/ext.rs, crates/fee/src/lib.rs, crates/issue/src/lib.rs, crates/issue/src/types.rs, crates/redeem/src/lib.rs, crates/redeem/src/types.rs, crates/replace/src/lib.rs, crates/replace/src/types.rs, crates/security/src/lib.rs, crates/sla/src/lib.rs, crates/sla/src/tests.rs, crates/staked-relayers/src/lib.rs, crates/staked-relayers/src/tests.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/tests.rs, crates/vault-registry/src/types.rs
=> chore: remove all runtime upgrades

crates/nomination/src/ext.rs, crates/nomination/src/lib.rs, crates/nomination/src/types.rs, crates/replace/src/ext.rs, crates/sla/src/ext.rs, crates/sla/src/lib.rs, crates/staked-relayers/src/ext.rs, crates/staked-relayers/src/lib.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/tests.rs, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/test_nomination.rs
=> refactor: trim nomination pallet for vault improvements

crates/btc-relay/src/mock.rs, crates/fee/src/mock.rs, crates/issue/src/ext.rs, crates/issue/src/mock.rs, crates/issue/src/tests.rs, crates/nomination/src/mock.rs, crates/nomination/src/tests.rs, crates/redeem/src/benchmarking.rs, crates/redeem/src/ext.rs, crates/redeem/src/mock.rs, crates/redeem/src/tests.rs, crates/refund/src/mock.rs, crates/replace/src/mock.rs, crates/sla/src/ext.rs, crates/sla/src/lib.rs, crates/sla/src/mock.rs, crates/staked-relayers/src/ext.rs, crates/staked-relayers/src/mock.rs, crates/staked-relayers/src/tests.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, crates/vault-registry/src/slash.rs, crates/vault-registry/src/tests.rs, crates/vault-registry/src/types.rs, parachain/runtime/src/lib.rs, parachain/runtime/tests/test_redeem.rs
=> feat: slashable vault for scalable nominator slashing

crates/issue/src/ext.rs, crates/issue/src/lib.rs, crates/issue/src/tests.rs, crates/redeem/src/ext.rs, crates/redeem/src/lib.rs, crates/redeem/src/tests.rs, crates/replace/src/ext.rs, crates/replace/src/lib.rs, crates/replace/src/tests.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/tests.rs, crates/vault-registry/src/types.rs, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/test_fee_pool.rs
=> refactor: rename slash_collateral to transfer_funds

Cargo.lock, crates/btc-relay/Cargo.toml, crates/btc-relay/src/mock.rs
=> refactor: trim btc-relay mock runtime

crates/exchange-rate-oracle/src/benchmarking.rs, crates/exchange-rate-oracle/src/lib.rs, crates/exchange-rate-oracle/src/mock.rs, crates/exchange-rate-oracle/src/types.rs, parachain/runtime/src/lib.rs
=> refactor: convert exchange rate oracle pallet to FRAME v2

crates/replace/src/ext.rs, crates/replace/src/lib.rs, crates/replace/src/tests.rs, crates/vault-registry/src/benchmarking.rs, crates/vault-registry/src/default_weights.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/tests.rs, parachain/runtime/tests/test_vault_registry.rs
=> refactor: lockAdditionalCollateral > depositCollateral

parachain/service/src/cumulus.rs
=> fix: use local cumulus import queue

parachain/service/src/grandpa.rs, parachain/src/command.rs
=> fix: expose rpc handlers

crates/parachain-tokens/src/lib.rs, crates/parachain-tokens/src/types.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade parachain-tokens to FRAME v2

crates/bitcoin/src/address.rs, crates/bitcoin/src/parser.rs, crates/bitcoin/src/types.rs, parachain/runtime/tests/mock/issue_testing_utils.rs
=> feat: implement scriptSig builders for the public key type

crates/security/src/lib.rs
=> feat: emit active block event

crates/redeem/src/ext.rs, crates/redeem/src/lib.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, crates/vault-registry/src/slash.rs, crates/vault-registry/src/tests.rs, crates/vault-registry/src/types.rs, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/test_redeem.rs, parachain/runtime/tests/test_replace.rs
=> [BREAKING]: distribute previously slashed collateral if redeemed

crates/sla/src/lib.rs, crates/sla/src/tests.rs, crates/sla/src/types.rs, crates/vault-registry/src/lib.rs, parachain/runtime/tests/test_redeem.rs, parachain/runtime/tests/test_vault_sla.rs
=> feat: withdraw all stake on liquidation

crates/issue/src/lib.rs, crates/issue/src/mock.rs, parachain/runtime/tests/mock/mod.rs, parachain/src/chain_spec.rs
=> fix: prevent issuing below dust value

Cargo.lock, Cargo.toml, parachain/rpc/src/lib.rs, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs, parachain/service/src/cumulus.rs, parachain/service/src/grandpa.rs, parachain/service/src/lib.rs, primitives/Cargo.toml, primitives/src/lib.rs
=> chore: extract primitives into their own crate

crates/nomination/src/default_weights.rs, crates/nomination/src/ext.rs, crates/nomination/src/lib.rs, crates/nomination/src/mock.rs, crates/nomination/src/tests.rs, crates/nomination/src/types.rs, crates/replace/src/ext.rs, crates/replace/src/lib.rs, crates/replace/src/mock.rs, crates/staked-relayers/src/mock.rs, parachain/runtime/src/lib.rs, parachain/runtime/tests/mock/mod.rs, parachain/runtime/tests/mock/nomination_testing_utils.rs, parachain/runtime/tests/test_nomination.rs, parachain/src/chain_spec.rs
=> refactor: simplify nomination pallet - operator not required

crates/nomination/src/lib.rs, crates/nomination/src/mock.rs, crates/nomination/src/types.rs, crates/replace/src/ext.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade nomination to FRAME v2

crates/issue/src/benchmarking.rs, crates/issue/src/lib.rs, crates/issue/src/mock.rs, crates/issue/src/tests.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade issue to FRAME v2

crates/sla/src/lib.rs, crates/sla/src/mock.rs, crates/sla/src/tests.rs
=> refactor: upgrade sla to FRAME v2

crates/bitcoin/src/parser.rs
=> fix: use nlocktime threshold const

crates/bitcoin/src/lib.rs, crates/btc-relay/src/lib.rs
=> chore: bitcoin and btc-relay lib doc comments

crates/redeem/src/lib.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade redeem to FRAME v2

crates/refund/src/lib.rs, crates/refund/src/tests.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade refund to FRAME v2

crates/replace/src/benchmarking.rs, crates/replace/src/lib.rs, crates/replace/src/mock.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade replace to FRAME v2

crates/staked-relayers/src/lib.rs, parachain/runtime/src/lib.rs
=> refactor: upgrade staked-relayers to FRAME v2

Cargo.lock, parachain/Cargo.toml, parachain/rpc/Cargo.toml, parachain/rpc/src/lib.rs, parachain/service/Cargo.toml, primitives/Cargo.toml, primitives/src/lib.rs
=> chore: remove runtime dependency from rpc crate

crates/fee/src/lib.rs, crates/nomination/src/ext.rs, crates/replace/src/mock.rs, crates/staked-relayers/src/mock.rs
=> refactor: upgrade fee to FRAME v2

crates/btc-relay/src/lib.rs
Fixed [this report](https://www.notion.so/interlay/f207ebc861994e2988fcbd32895561f6?v=b4dc7a68fa584fabbabc646063b5d02e&p=35f9600ffe6c4c64b515ebc9fd33b544)
=> fix: use DIFFICULTY_ADJUSTMENT_INTERVAL consistently

crates/bitcoin/src/parser.rs
Reported [here](https://www.notion.so/interlay/f207ebc861994e2988fcbd32895561f6?v=b4dc7a68fa584fabbabc646063b5d02e&p=035491b98a6c4eecb22610d837e88fe8)
=> fix: if the witness flag is set, check that a witness is actually used

primitives/src/lib.rs
=> feat: add intr token

crates/nomination/src/lib.rs
To accompany https://github.com/interlay/interbtc-spec/pull/3
=> fix: ensure parachain is running on nomination opt-out

README.md, crates/fee/src/lib.rs, crates/vault-registry/src/lib.rs, parachain/runtime/src/lib.rs, parachain/src/chain_spec.rs, primitives/src/lib.rs, standalone/runtime/src/lib.rs, standalone/src/chain_spec.rs
=> refactor: InterBTC -> interBTC

standalone/src/lib.rs
=> chore: add lib to standalone src

parachain/runtime/src/lib.rs, standalone/runtime/src/lib.rs
=> feat: implement OnDust to sweep reaped funds into FeeAccount

.gitlab-ci.yml
=> chore: gitlab ci should use artifact variable

crates/replace/src/lib.rs
=> fix: no need to insert replace request twice

.gitlab-ci.yml
- https://hub.docker.com/repository/docker/interlayhq/interbtc
=> feat: publish images to dockerhub

crates/vault-registry/src/lib.rs
=> fix: add DecreaseToBeReplacedTokens event

crates/reward/src/lib.rs
=> feat: add distribute reward event to reward pallet

crates/security/src/tests.rs
=> chore: fix security test names

crates/redeem/src/ext.rs, crates/redeem/src/lib.rs
The code can be simplified now that we no longer transfer to fee pool
=> refactor(redeem): transfer whole punishment to user directly

crates/staking/README.md
=> feat: staking pallet readme

Cargo.lock, crates/issue/src/mock.rs, crates/nomination/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/relay/src/mock.rs, crates/replace/src/mock.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, crates/vault-registry/src/types.rs, parachain/runtime/src/lib.rs, standalone/runtime/src/lib.rs
=> refactor: bind reward config to vault-registry

primitives/src/lib.rs
=> chore: add doc comments to all primitive types

crates/staking/README.md, crates/staking/src/lib.rs, crates/staking/src/tests.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/types.rs
=> refactor: vault should be slashed first on theft

crates/redeem/src/lib.rs, crates/redeem/src/tests.rs
To accompany: https://github.com/interlay/interbtc-spec/pull/29
=> refactor: vault can self-redeem without fees

crates/refund/src/lib.rs, crates/refund/src/mock.rs, crates/refund/src/tests.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_redeem.rs, standalone/runtime/tests/test_refund.rs
=> chore: add refund tests based on spec conditions

crates/staking/src/lib.rs, standalone/runtime/tests/test_issue.rs
=> fix: don't withdraw stake if amount is zero

crates/exchange-rate-oracle/src/lib.rs
=> fix: oracle metadata name

crates/exchange-rate-oracle/rpc/runtime-api/src/lib.rs, crates/exchange-rate-oracle/rpc/src/lib.rs, crates/issue/src/lib.rs, crates/redeem/src/lib.rs, crates/redeem/src/tests.rs, crates/relay/src/benchmarking.rs, crates/relay/src/ext.rs, crates/relay/src/types.rs, crates/replace/src/lib.rs, crates/replace/src/tests.rs, crates/replace/src/types.rs, crates/vault-registry/rpc/runtime-api/src/lib.rs, crates/vault-registry/rpc/src/lib.rs, parachain/runtime/src/lib.rs, primitives/src/lib.rs, rpc/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/issue_testing_utils.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/mock/redeem_testing_utils.rs, standalone/runtime/tests/test_replace.rs
=> refactor!: merge duplicate numerical generics everywhere

crates/bitcoin/src/parser.rs, crates/bitcoin/src/script.rs, crates/bitcoin/src/types.rs, crates/fee/src/lib.rs, crates/fee/src/mock.rs, crates/issue/src/mock.rs, crates/nomination/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/relay/src/ext.rs, crates/relay/src/lib.rs, crates/relay/src/mock.rs, crates/relay/src/tests.rs, crates/replace/src/mock.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, crates/vault-registry/src/types.rs, parachain/runtime/src/lib.rs, parachain/src/chain_spec.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_staked_relayers.rs, standalone/src/chain_spec.rs
=> feat: theft fee for correct report

parachain/runtime/src/lib.rs, parachain/src/chain_spec.rs, primitives/src/lib.rs
=> feat: add kusama currencies

crates/btc-relay/src/lib.rs, crates/issue/src/lib.rs, crates/redeem/src/lib.rs, crates/replace/src/lib.rs
=> refactor: replace redundant checks with try_get

parachain/src/chain_spec.rs, parachain/src/command.rs
=> feat: add westend parachain config

crates/issue/src/types.rs, crates/staking/src/lib.rs, crates/staking/src/tests.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/types.rs
=> fix: withdraw for remaining to_be_redeemed first

crates/oracle/src/ext.rs, crates/oracle/src/lib.rs, crates/oracle/src/tests.rs, crates/oracle/src/types.rs, crates/security/src/lib.rs
=> fix: consider oracle to be offline when ANY currency is outdated

docs/rococo.md
=> fix: register parathread img link

parachain/src/cli.rs, parachain/src/command.rs
=> feat: add build command to generate a chain-spec with parachain-id

parachain/src/chain_spec.rs, parachain/src/command.rs
=> feat: add kusama parachain config

parachain/runtime/src/lib.rs, standalone/runtime/src/lib.rs
=> chore: reset spec_version to 1

parachain/runtime/src/lib.rs
=> chore: set parent chain to kusama

primitives/src/lib.rs
=> feat: introduce currency info trait

parachain/src/command.rs
=> chore: set the default para id to something sensible

crates/currency/src/lib.rs, crates/staking/src/lib.rs, rust-toolchain.toml
=> chore: use nightly-2021-08-01

crates/security/src/lib.rs
=> refactor: remove unused security errors

crates/issue/src/lib.rs, crates/issue/src/types.rs, crates/redeem/src/lib.rs, crates/redeem/src/types.rs, crates/refund/src/lib.rs, crates/refund/src/types.rs, crates/relay/src/ext.rs, crates/replace/src/lib.rs, crates/replace/src/types.rs
=> refactor: add default request type aliases

Cargo.lock, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs, parachain/src/chain_spec.rs
=> feat: integrate orml-vesting for kint distribution

crates/fee/src/mock.rs, crates/issue/src/mock.rs, crates/nomination/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/relay/src/mock.rs, crates/replace/src/mock.rs, crates/reward/src/lib.rs, crates/vault-registry/src/mock.rs, parachain/runtime/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/test_fee_pool.rs
=> refactor!: reward pallet does not need to be instantiable

parachain/runtime/src/lib.rs
=> chore: parachain is limited to 12s block times

crates/relay/src/lib.rs
=> refactor!: use storage double map to store theft reports

Cargo.lock, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs, parachain/src/chain_spec.rs, primitives/src/lib.rs
=> feat: integrate pallet-elections-phragmen for general council voting

standalone/runtime/tests/mock/issue_testing_utils.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/mock/redeem_testing_utils.rs, standalone/runtime/tests/test_issue.rs, standalone/runtime/tests/test_redeem.rs, standalone/runtime/tests/test_refund.rs, standalone/runtime/tests/test_replace.rs, standalone/runtime/tests/test_staked_relayers.rs
=> test: report double payment as theft

standalone/runtime/tests/test_refund.rs
Need to test refund and replace double spending after @gregdhill merges his PR
=> test: Wrong btc amounts for refund

standalone/runtime/tests/test_refund.rs
=> fix: outdated refund integration tests

Cargo.lock, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs, parachain/src/chain_spec.rs
This reverts commit 0623e4cd6fd7721cb07b5c90b117cd0d136885d4.
=> Revert "feat: integrate collator-selection and session pallets"

Cargo.lock, crates/collator-setter/Cargo.toml, crates/collator-setter/src/lib.rs, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs
=> feat: tmp pallet to force set collators in aura

parachain/src/chain_spec.rs, parachain/src/command.rs, scripts/prepare-test-net.sh
=> feat: add interlay (polkadot) chain spec

.github/workflows/cargo-docs.yml, .github/workflows/cargo-test.yml
Pending https://github.com/actions-rs/toolchain/issues/126
=> chore: use rust toolchain from config

crates/democracy/src/lib.rs
=> feat: re-add cancel_proposal root dispatchable fn

crates/democracy/README.md, crates/democracy/src/lib.rs, crates/democracy/src/tests.rs, crates/democracy/src/tests/preimage.rs
=> refactor: remove separate democracy operational origin

parachain/runtime/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_governance.rs
=> fix: governance integration tests

README.md, crates/btc-relay/README.md, crates/btc-relay/src/lib.rs, crates/currency/Cargo.toml, crates/fee/src/lib.rs, crates/issue/src/lib.rs, crates/oracle/README.md, crates/oracle/src/lib.rs, crates/redeem/src/lib.rs, crates/replace/src/lib.rs, crates/security/README.md, crates/security/src/lib.rs, crates/vault-registry/README.md, crates/vault-registry/src/lib.rs
=> chore: replace old gitlab spec links

Dockerfile
=> fix: standalone docker build image

crates/reward/src/lib.rs
Reverts https://github.com/interlay/interbtc/commit/1b1d83cf31a3c3a7f8fb21fda37ec14c4d9c4213
=> refactor: reward pallet **should** be instantiable

crates/currency/src/lib.rs, parachain/runtime/src/lib.rs, standalone/runtime/src/lib.rs
=> feat: send transaction fees to author

Cargo.lock, parachain/runtime/Cargo.toml, parachain/runtime/src/lib.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_multisig.rs
We require this to store the KINT tokens in a multi-sig for the Kintsugi Labs account
=> feat: multisig pallet

Cargo.lock, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/src/chain_spec.rs
=> feat: add orml-vesting to standalone runtime

standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_multisig.rs
=> test: multisig should transfer vested

standalone/runtime/tests/test_governance.rs
=> test: lock vested tokens in escrow

crates/democracy/src/lib.rs
=> feat: add fast-track event to democracy

parachain/runtime/src/lib.rs
=> chore: bump spec version for 1.4.1

Cargo.lock, crates/annuity/Cargo.toml, crates/annuity/src/lib.rs, crates/annuity/src/mock.rs, crates/annuity/src/tests.rs, crates/fee/src/lib.rs, crates/reward/src/lib.rs, crates/reward/src/tests.rs, crates/supply/src/lib.rs, parachain/runtime/interlay/Cargo.toml, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/Cargo.toml, parachain/runtime/kintsugi/src/lib.rs, parachain/src/chain_spec.rs
=> feat: add annuity pallet to distribute block rewards

crates/fee/src/mock.rs, crates/issue/src/benchmarking.rs, crates/issue/src/mock.rs, crates/nomination/src/benchmarking.rs, crates/nomination/src/mock.rs, crates/redeem/src/benchmarking.rs, crates/redeem/src/mock.rs, crates/refund/src/benchmarking.rs, crates/refund/src/mock.rs, crates/relay/src/benchmarking.rs, crates/relay/src/mock.rs, crates/replace/src/benchmarking.rs, crates/replace/src/mock.rs, crates/reward/src/lib.rs, crates/reward/src/mock.rs, crates/reward/src/tests.rs, crates/vault-registry/src/benchmarking.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
=> refactor: distinguish reward id for separate stake-to-vote rewards

parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/test_governance.rs
I also added several comments with todo's, please also check these
=> test: governance tests

crates/annuity/src/lib.rs, crates/annuity/src/mock.rs, crates/fee/src/lib.rs, crates/nomination/src/ext.rs, crates/nomination/src/lib.rs, crates/nomination/src/mock.rs, crates/nomination/src/types.rs, crates/relay/src/mock.rs, crates/replace/src/mock.rs, crates/reward/src/lib.rs, crates/staking/src/lib.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/types.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/src/chain_spec.rs, standalone/runtime/src/lib.rs
=> feat: integrate escrow annuity distribution

parachain/runtime/interlay/src/lib.rs
=> refactor: use polkadot constants for interlay runtime currencies

Cargo.lock, crates/annuity/src/lib.rs, crates/annuity/src/tests.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/runtime/tests/test_annuity.rs, standalone/src/chain_spec.rs
Annuity used to transfer a fraction of its current holdings every block, effectively making this an exponential decay function rather than a linear one. With this pr, it is made linear
=> fix: annuity amount

primitives/src/lib.rs
To be in line with e.g. acala: https://github.com/AcalaNetwork/Acala/blob/master/primitives/src/currency.rs#L183
=> refactor: assign explicit indices to TokenSymbol items

standalone/runtime/tests/test_governance.rs
- Adds an integration test that tries to participate in governance (propose, second, vote) with and without having tokens in escrow.
=> tests: ensure governance participation only possible with staked tokens

crates/escrow/src/lib.rs, crates/fee/src/lib.rs, crates/fee/src/mock.rs, crates/issue/src/mock.rs, crates/nomination/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/relay/src/mock.rs, crates/replace/src/mock.rs, crates/reward/src/lib.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/mock.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/test_fee_pool.rs
=> refactor: remove RewardsCurrencyAdapter

crates/fee/src/lib.rs, crates/fee/src/mock.rs, crates/issue/src/mock.rs, crates/nomination/src/benchmarking.rs, crates/nomination/src/ext.rs, crates/nomination/src/lib.rs, crates/nomination/src/mock.rs, crates/nomination/src/types.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/relay/src/mock.rs, crates/replace/src/mock.rs, crates/staking/src/lib.rs, crates/vault-registry/src/ext.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/test_fee_pool.rs
=> refactor: remove StakingCurrencyAdapter

standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_annuity.rs, standalone/runtime/tests/test_fee_pool.rs
=> refactor: split escrow / vault rewards in standalone runtime

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
=> refactor: group runtime pallet ids

crates/annuity/src/lib.rs
=> chore: add non-zero weight on annuity extrinsic

README.md
=> chore: specify additional crates in readme

docs/xcm-config.json
=> fix: bump validation_upgrade_delay to 20

crates/vault-registry/src/lib.rs
=> refactor: compute vault-registry pallet id at runtime

crates/issue/src/benchmarking.rs, crates/issue/src/lib.rs, crates/issue/src/types.rs, crates/nomination/src/types.rs, crates/redeem/src/benchmarking.rs, crates/redeem/src/lib.rs, crates/redeem/src/tests.rs, crates/redeem/src/types.rs, crates/refund/src/lib.rs, crates/refund/src/types.rs, crates/relay/src/lib.rs, crates/relay/src/types.rs, crates/replace/src/benchmarking.rs, crates/replace/src/lib.rs, crates/replace/src/types.rs, crates/vault-registry/src/benchmarking.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/types.rs
=> refactor: cleanup unnecessary balance type aliases

parachain/runtime/kintsugi/src/lib.rs
=> chore: bump kintsugi spec version to 7 for 1.5.4

Cargo.lock, parachain/runtime/interlay/Cargo.toml, parachain/runtime/kintsugi/Cargo.toml, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/src/chain_spec.rs
=> feat: add supply pallet and token distribution to standalone runtime

crates/escrow/src/lib.rs, crates/escrow/src/tests.rs
See: https://github.com/interlay/interbtc/pull/430
=> chore: address SBPM1 feedback on escrow pallet

parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/tests/test_multisig.rs
=> chore: update kintsugi labs addresses

parachain/runtime/kintsugi/src/lib.rs
=> refactor: add additional addresses for kintsugi labs

crates/supply/src/mock.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
=> fix: escrow annuity pallet should use correct provider

Cargo.lock, parachain/runtime/kintsugi/Cargo.toml, parachain/runtime/kintsugi/src/lib.rs, parachain/src/chain_spec.rs
=> refactor!: remove sudo pallet on kintsugi

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs
It turns out that `type FeeMultiplierUpdate = ();` sets the multiplier to zero, which caused the fee charged for the per-function weight to be zero. Now we use the dynamic multiplier based on how full the blocks are. New value is the one used by acala
=> fix: use dynamic transaction fee multiplier (used to be 0)

parachain/runtime/kintsugi/src/lib.rs
=> chore: annotate system accounts on kintsugi runtime

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
=> chore: remove unused constants from runtimes

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
Replaces https://github.com/interlay/interbtc/pull/445
=> refactor: vesting should use system height

Cargo.lock, parachain/Cargo.toml, parachain/src/command.rs, parachain/src/service.rs
=> feat: integrate rpcs in parachain service

parachain/src/chain_spec.rs, standalone/src/chain_spec.rs
=> fix: supply start height should be after end of year 4

parachain/src/chain_spec.rs
Should make testing easier and reduce reliance on testnet funding.
=> feat: add endowed accounts to chain spec

Cargo.lock, parachain/src/chain_spec.rs
=> fix: update ss58 registry and add prefix to properties

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs
=> refactor: use native currency for parachain fees

parachain/res/interlay.json, parachain/res/kintsugi.json, parachain/src/chain_spec.rs
=> chore: order kintsugi and interlay currencies in properties

Cargo.lock, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs, primitives/src/lib.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_multisig.rs
=> refactor: re-enable transaction weights, harmonize runtimes

crates/escrow/src/lib.rs, crates/reward/src/lib.rs
=> refactor: base escrow rewards on amount * period

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs
As suggested in e.g. https://github.com/paritytech/polkadot/issues/4165
=> fix: disallow unnecessary xcm calls

docs/rococo.md
=> chore: bump rococo docs to v0.9.15

crates/democracy/src/lib.rs
=> chore: remove unused democracy import and deny warnings

standalone/runtime/src/lib.rs, standalone/runtime/tests/mock/issue_testing_utils.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/mock/nomination_testing_utils.rs, standalone/runtime/tests/mock/redeem_testing_utils.rs, standalone/runtime/tests/mock/replace_testing_utils.rs, standalone/runtime/tests/test_annuity.rs, standalone/runtime/tests/test_escrow.rs, standalone/runtime/tests/test_governance.rs, standalone/runtime/tests/test_multisig.rs, standalone/runtime/tests/test_redeem.rs, standalone/runtime/tests/test_replace.rs
=> test: ensure escrow reward stake is escrow balance

Cargo.lock, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs, standalone/runtime/src/lib.rs
State version should be 0 according to basti in element.
=> fix: set state_version to 0 and update deps

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs, standalone/runtime/src/lib.rs
=> feat: add standalone fee adjustment

rust-toolchain.toml
This should fix the rust-doc errors the CI was having
=> chore: upgrade compiler version

parachain/src/service.rs
=> fix: hardcode slot duration

parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs
=> chore: bump spec versions for 1.8.1

standalone/runtime/src/lib.rs, standalone/src/chain_spec.rs
=> chore: order currencies in standalone properties

crates/issue/src/lib.rs
=> refactor!: remove unused issue errors and add doc strings

crates/replace/src/lib.rs
=> refactor!: cleanup replace errors and add doc strings

crates/escrow/src/lib.rs, crates/escrow/src/tests.rs
=> refactor!: more specific escrow errors and doc strings

parachain/res/interlay.json
=> feat: add interlay bootnodes

parachain/src/chain_spec.rs, standalone/src/chain_spec.rs
=> chore: remove unused band oracle account

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs, standalone/runtime/src/lib.rs
Will be required to call `update_rewards` in the community governance proposal.
=> refactor: expose call on VaultAnnuity for root update_rewards

crates/security/src/lib.rs
=> refactor!: cleanup security errors and add doc strings

crates/redeem/src/lib.rs, crates/redeem/src/tests.rs, standalone/runtime/tests/test_redeem.rs
=> refactor!: cleanup redeem errors and add doc strings

crates/oracle/src/lib.rs, crates/oracle/src/tests.rs, crates/redeem/src/benchmarking.rs
=> fix: oracle shouldn't pay fees

parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs
=> chore: bump runtime versions for 1.9.0

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, .github/workflows/draft-release.yml, .gitlab-ci.yml, scripts/history.sh, scripts/release_notes.sh, scripts/srtool_info.py
=> Chore: github action to build draft release

.chglog/config.yml
=> chore: chglog should match breaking syntax

parachain/src/chain_spec.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_fee_pool.rs, standalone/src/chain_spec.rs
=> chore: lower issue fee to 0.15% at genesis

crates/fee/src/lib.rs
=> refactor!: cleanup fee errors and add doc strings

crates/reward/src/lib.rs
=> refactor!: cleanup reward errors and add doc strings

crates/staking/src/lib.rs
=> refactor!: cleanup staking errors and add doc strings

parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs
=> chore: bump kintsugi & testnet spec_version for 1.10.0

crates/btc-relay/src/lib.rs
This time merging to the correct branch..
=> fix: remove output limit on issue transaction

parachain/res/kintsugi.json
Removes unused kintsugi bootnode
=> Chore: fix kintsugi bootnodes

parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs
=> chore: bump kintsugi & testnet spec_version for 1.11.0

parachain/runtime/interlay/src/lib.rs
=> chore: bump interlay spec version

parachain/runtime/interlay/src/lib.rs
=> chore: re-enable transaction fees on interlay

parachain/runtime/interlay/src/lib.rs, parachain/src/chain_spec.rs
=> refactor!: remove sudo from interlay runtime

crates/replace/src/lib.rs, crates/replace/src/tests.rs, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/mock/replace_testing_utils.rs, standalone/runtime/tests/test_replace.rs
=> feat: allow cancelled replace requests to be executed

parachain/res/interlay.json, parachain/res/kintsugi.json
=> chore: add bitcoinNetwork to pre-existing parachain chain specs

crates/issue/src/lib.rs, crates/redeem/src/lib.rs, crates/replace/src/lib.rs
=> feat!: add events for issue, redeem and replace period changes

parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs
=> chore: bump spec versions for 1.13.0

parachain/Cargo.toml, parachain/runtime/testnet/Cargo.toml, parachain/runtime/testnet/src/constants.rs, parachain/runtime/testnet/src/xcm_config.rs
=> feat: configurable testnet for interlay currencies

Cargo.lock, crates/escrow/src/lib.rs, crates/escrow/src/tests.rs, standalone/runtime/Cargo.toml, standalone/runtime/tests/mock/mod.rs, standalone/runtime/tests/test_escrow.rs, standalone/runtime/tests/test_vault_registry.rs
Also changed the LockAmountTooLarge error since it was a misnomer
=> test: some theft and escrow related tests

crates/fee/src/default_weights.rs, crates/fee/src/lib.rs, crates/fee/src/mock.rs, crates/fee/src/tests.rs, crates/issue/src/mock.rs, crates/nomination/src/mock.rs, crates/redeem/src/mock.rs, crates/refund/src/mock.rs, crates/relay/src/mock.rs, crates/replace/src/mock.rs, crates/vault-registry/src/mock.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet/src/lib.rs, standalone/runtime/src/lib.rs
Adds setter extrinsics for the storage fields in the Fee pallet.
=> feat(fee): storage setter extrinsics

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: bump spec versions for 1.15.0

parachain/runtime/runtime-tests/src/relaychain/polkadot_cross_chain_transfer.rs
I needed these modifications to determine how much we need to allocate for opening hrmp channels
=> test: hrmp setup cost

crates/oracle/src/lib.rs
In my (unpushed) RBF branch on the clients I need to listen to oracle events. But rather than listening to `FeedValues`, we should listen to updates to the aggregate since they might not be the same. The event contains `Option<rate>` which would be `None` when the aggregate gets cleared due to inactive oracles.
=> feat!: added event for when the oracle aggregate gets updated

crates/democracy/src/lib.rs
=> feat: add fast_track_default to schedule with default VotingPeriod

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: set parachain runtime spec_version to 1017000

crates/currency/src/lib.rs, rust-toolchain.toml
=> chore: upgrade to nightly-2022-06-20

parachain/src/command.rs
Very minor, but makes more sense.
=> chore: rename staging chain specs

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: set spec_version for 1.18.0

primitives/src/lib.rs
Closes #612
See: https://github.com/polkadot-js/apps/issues/7645#issuecomment-1138752455
=> fix: enums exposed over RPC should use camelCase

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: set SpendPeriod to 1h and set spec_version for 1.18.1

crates/currency/src/lib.rs, rust-toolchain.toml
This reverts commit 374b4c9ceaf1b97d89b3be80391dec1fa4ce1a06.
=> chore: use nightly-2022-06-20

crates/currency/src/amount.rs, crates/currency/src/lib.rs, crates/oracle/src/lib.rs, crates/refund/src/lib.rs, crates/vault-registry/src/lib.rs, crates/vault-registry/src/mock.rs, crates/vault-registry/src/tests.rs, crates/vault-registry/src/types.rs
=> [BREAKING] chore!: use ArithmeticError in other pallets

parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: harmonize testnet accounts

parachain/src/chain_spec/interlay.rs, parachain/src/chain_spec/kintsugi.rs, parachain/src/chain_spec/testnet_interlay.rs, parachain/src/chain_spec/testnet_kintsugi.rs
=> chore: harmonize chain specs with live networks

docs/sovereign_accounts.md
=> chore: document sovereign account calculation

parachain/runtime/kintsugi/src/lib.rs
=> chore: remove kintsugi aura migration

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
=> fix: spend origin should allow max for root

crates/reward/src/tests.rs
Added test that helps with debugging potential reward issues
=> test: reward tests from specific state

Cargo.lock, parachain/Cargo.toml, parachain/runtime/interlay/Cargo.toml, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/Cargo.toml, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/Cargo.toml, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/Cargo.toml, parachain/runtime/testnet-kintsugi/src/lib.rs, parachain/src/cli.rs, parachain/src/command.rs
Allows us to use try-runtime. Usage is documented here: https://www.notion.so/interlay/Try-runtime-f722a442dfbd4aa68f9fe2a278222f70
=> feat: try-runtime support

parachain/res/interlay.json, parachain/res/kintsugi.json
Move existing boot nodes to new hosts.
=> Chore: update bootnodes

parachain/runtime/kintsugi/src/lib.rs
=> chore: remove executed kintsugi collator-selection migration

crates/fee/src/lib.rs, crates/fee/src/types.rs, crates/issue/src/lib.rs, crates/oracle/src/types.rs, crates/redeem/src/types.rs, crates/replace/src/types.rs
=> chore: remove unused storage versions, set issue default to v4

.github/workflows/cargo-docs.yml
=> chore: add protobuf-compiler to docs build

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
As done in https://github.com/paritytech/cumulus/commit/7cc2878e76348f4c83f2cac033e0f96e10b8efdb
=> fix: use aura timestamp hook

crates/issue/src/mock.rs, crates/nomination/src/mock.rs, crates/oracle/README.md, crates/oracle/src/lib.rs, crates/oracle/src/mock.rs, crates/oracle/src/types.rs, crates/redeem/src/mock.rs, crates/replace/src/mock.rs, crates/vault-registry/src/mock.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
Required addition for #769, will allow us to update the capacity rewards pool when the exchange rate changes.
=> feat: add hook for aggregate change

Cargo.lock, Cargo.toml, parachain/runtime/testnet-kintsugi/Cargo.toml, parachain/runtime/testnet-kintsugi/src/constants.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, parachain/runtime/testnet-kintsugi/src/zenlink.rs, primitives/Cargo.toml, primitives/src/lib.rs
=> Zenlink integration (testnet-kintsugi)

.github/workflows/cargo-test.yml
=> chore: use active toolchain in ci tests

crates/vault-registry/src/migration.rs
This passes now. The problem earlier was that we didn't account for liquidated collateral
=> test: TotalUserVaultCollateral check in migration

Cargo.lock, crates/democracy/Cargo.toml, crates/democracy/src/benchmarking.rs, crates/democracy/src/lib.rs, crates/democracy/src/tests.rs, crates/democracy/src/tests/public_proposals.rs, crates/democracy/src/tests/voting.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/interlay/src/xcm_config.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/kintsugi/src/xcm_config.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, standalone/runtime/src/lib.rs, standalone/runtime/tests/test_governance.rs
=> Chore: backport xcm and tabling

parachain/src/service.rs
=> refactor: always use 12000 slot duration

crates/loans/src/lib.rs
`AccountEarned` is only stored for helping the UI and the way it is computed is wrong. To fix it, we would need to call `accrue_interest()` on each Lend Token transfer, along with the computation that actually updates `AccountEarned`. I am removing this because it's inaccurate and the fix is too computationally expensive.
The formula is correct in Parallel's case because they don't allow users to transfer lend tokens.
=> feat(loans): remove `AccountEarned` storage

parachain/runtime/testnet-kintsugi/Cargo.toml, primitives/Cargo.toml
See: https://github.com/zenlinkpro/Zenlink-DEX-Module/pull/57
=> chore: use zenlink rev with custom exchange fees

docs/pallet_accounts.md
=> docs: add examples to derive pallet accounts

Cargo.lock, crates/annuity/Cargo.toml, crates/bitcoin/Cargo.toml, crates/btc-relay/Cargo.toml, crates/currency/Cargo.toml, crates/escrow/Cargo.toml, crates/fee/Cargo.toml, crates/issue/Cargo.toml, crates/loans/Cargo.toml, crates/nomination/Cargo.toml, crates/oracle/Cargo.toml, crates/redeem/Cargo.toml, crates/replace/Cargo.toml, crates/reward/Cargo.toml, crates/security/Cargo.toml, crates/staking/Cargo.toml, crates/supply/Cargo.toml, crates/vault-registry/Cargo.toml, parachain/runtime/interlay/Cargo.toml, parachain/runtime/kintsugi/Cargo.toml, parachain/runtime/runtime-tests/Cargo.toml, parachain/runtime/testnet-interlay/Cargo.toml, parachain/runtime/testnet-kintsugi/Cargo.toml, rust-toolchain.toml, standalone/runtime/Cargo.toml
=> chore: upgrade to nightly-2022-12-15

Cargo.lock, crates/farming/Cargo.toml
=> chore: update cargo lock

crates/loans/src/lib.rs, crates/loans/src/types.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
Depends on https://github.com/interlay/interbtc/pull/865.
Closes https://github.com/interlay/interbtc/issues/756.
=> Lending doc comments

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs
=> fix: update capacity on exchange rate change

crates/vault-registry/src/lib.rs, crates/vault-registry/src/pool_manager.rs, crates/vault-registry/src/types.rs, standalone/runtime/tests/mock/reward_testing_utils.rs, standalone/runtime/tests/test_fee_pool.rs
Closes https://github.com/interlay/interbtc/issues/881
=> fix: set stake in reward pool to 0 when vault is not accepting new issues

crates/reward/rpc/runtime-api/src/lib.rs, crates/reward/rpc/src/lib.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
=> feat: add rpc to compute farming reward

crates/loans/src/lib.rs, crates/loans/src/tests/edge_cases.rs, crates/loans/src/tests/interest_rate.rs
Fixes the first high-severity bug identified in Compound's [audit from OpenZeppelin](https://blog.openzeppelin.com/compound-audit/).
=> test(loans): small loans may accrue no interest

Cargo.lock, crates/loans/Cargo.toml, crates/loans/src/mock.rs, crates/loans/src/tests/edge_cases.rs
Ensures that batched loans accrue full interest, even though interest is lazily accrued.
=> test(loans): batched loans accrue interest

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: bump spec versions to 1021007

crates/loans/src/tests/edge_cases.rs, crates/vault-registry/src/migration.rs, parachain/runtime/testnet-interlay/src/dex.rs, parachain/runtime/testnet-kintsugi/src/dex.rs
Annotate loans test and remove now unused dex imports
=> chore: resolve clippy warnings

crates/dex-general/rpc/runtime-api/src/lib.rs, crates/dex-general/rpc/src/lib.rs, crates/dex-general/src/rpc.rs, crates/dex-general/src/swap/mod.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs, standalone/runtime/src/lib.rs
See: https://github.com/zenlinkpro/Zenlink-DEX-Module/pull/60
=> feat: add dex-general rpc to calculate share amounts

parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, parachain/runtime/testnet-kintsugi/src/lib.rs
=> chore: bump spec versions to 1021008

crates/dex-swap-router/src/benchmarking.rs, crates/dex-swap-router/src/lib.rs, crates/dex-swap-router/src/mock.rs, crates/dex-swap-router/src/test.rs, parachain/runtime/testnet-interlay/src/dex.rs, parachain/runtime/testnet-kintsugi/src/dex.rs
=> refactor: only use one currency id in swap router

parachain/runtime/interlay/src/lib.rs
Closes https://github.com/interlay/interbtc/issues/937
=> fix: run vault capacity migration on interlay network

crates/democracy/src/lib.rs, crates/democracy/src/tests/fast_tracking.rs, crates/democracy/src/tests/voting.rs, standalone/runtime/tests/test_governance.rs
Closes https://github.com/interlay/interbtc/issues/942
=> refactor: change default vote threshold to SuperMajorityApprove

crates/dex-swap-router/src/lib.rs, crates/dex-swap-router/src/test.rs
Filters invalid routes in `swap_exact_token_for_tokens_through_stable_pool` - force the output of each route to have the same currency as the input of the next.
Addresses https://github.com/interlay/srlabs-audit/issues/9
=> fix: restrict dex router paths

Cargo.lock, parachain/runtime/common/Cargo.toml, parachain/runtime/common/src/lib.rs, parachain/runtime/interlay/src/xcm_config.rs, parachain/runtime/kintsugi/src/xcm_config.rs, parachain/runtime/runtime-tests/src/relaychain/kusama_cross_chain_transfer.rs, parachain/runtime/runtime-tests/src/relaychain/polkadot_cross_chain_transfer.rs, parachain/runtime/testnet-interlay/src/xcm_config.rs, parachain/runtime/testnet-kintsugi/src/xcm_config.rs
Addresses https://github.com/interlay/interbtc/issues/959
=> fix: disallow xcm messages containing transact

crates/vault-registry/src/lib.rs, crates/vault-registry/src/tests.rs
=> fix: don't allow vaults to withdraw below minimum

crates/loans/src/tests/liquidate_borrow.rs
The only usage of `liquidate_incentive_reserved_factor` I could find was in `liquidated_transfer`, which only gets called from `liquidate_borrow` as far as I can tell. This test checks that having it set to 0 doesn't cause any problems
=> test: liquidation with liquidate_incentive_reserved_factor=0

crates/dex-general/src/fee/tests.rs, crates/dex-general/src/lib.rs
See: https://github.com/zenlinkpro/Zenlink-DEX-Module/pull/64/commits/e3fd328edcccef2a3a7fcfbd5326671ee14f36fa
=> test: assert higher fee_point decreases protocol fee

crates/bitcoin/src/address.rs
=> fix: make sure address parsing has complexity O(1)

crates/dex-general/src/lib.rs, crates/dex-general/src/swap/mod.rs, crates/dex-stable/src/lib.rs
Closes https://github.com/interlay/interbtc/issues/1032
=> [BREAKING] refactor!: use named events in dex-general and add fee updates

Cargo.lock, crates/dex-general/src/fee/mock.rs, crates/dex-general/src/lib.rs, crates/dex-general/src/primitives.rs, crates/dex-general/src/swap/mock.rs, crates/dex-general/src/swap/mod.rs, crates/dex-general/src/swap/tests.rs, crates/dex-general/src/traits.rs, crates/dex-stable/src/base_pool.rs, crates/dex-stable/src/lib.rs, crates/dex-stable/src/mock.rs, crates/dex-swap-router/src/mock.rs, parachain/runtime/kintsugi/src/dex.rs, parachain/runtime/testnet-interlay/src/dex.rs, parachain/runtime/testnet-kintsugi/src/dex.rs, primitives/Cargo.toml, primitives/src/lib.rs
Some cleanups I made while working on a separate issue
=> refactor: remove AssetInfo, separate bootstrap account, cleanup errors

crates/currency/src/amount.rs, crates/issue/src/benchmarking.rs, crates/issue/src/lib.rs, crates/issue/src/migration.rs, crates/issue/src/tests.rs, crates/issue/src/types.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/runtime/testnet-interlay/src/lib.rs, primitives/src/lib.rs, standalone/runtime/tests/mock/issue_testing_utils.rs, standalone/runtime/tests/test_issue.rs
To accompany https://github.com/interlay/interbtc/pull/1054 
I tested the migration with chopsticks.
=> feat: issue griefing collateral in selectable currency

crates/dex-general/Cargo.toml, crates/dex-general/src/swap/tests.rs
Still need to add a few other test cases, but I quite like these property tests, they're very simple to set up. I think we should look into using it also in other parts of the code, i.e. loans, staking, etc.
=> test: add amm property tests

Cargo.lock, parachain/runtime/common/Cargo.toml, parachain/runtime/common/src/lib.rs, parachain/runtime/interlay/src/lib.rs, parachain/runtime/kintsugi/src/lib.rs, parachain/src/chain_spec/interlay.rs, parachain/src/chain_spec/kintsugi.rs, parachain/src/chain_spec/testnet_interlay.rs, parachain/src/chain_spec/testnet_kintsugi.rs, parachain/src/cli.rs
Closes https://github.com/interlay/interbtc/issues/955
=> refactor: allow using instant-seal on all runtimes

crates/dex-general/src/fee/tests.rs
Closes https://github.com/interlay/interbtc/issues/1094 .
The test checks that registering with 0 fees works, and that swaps are actually zero-cost (ignoring rounding)
=> test: sanity check that zero swap fees work

.github/workflows/benchmark.yml, scripts/benchmark.sh
Closes https://github.com/interlay/interbtc/issues/1009
=> chore: add weights automation

crates/collator-selection/src/benchmarking.rs, crates/collator-selection/src/mock.rs
Closes https://github.com/interlay/interbtc/issues/954
=> chore: use v2 benchmark syntax for collator-selection

.gitignore, scripts/fetch_bitcoin_data.py
Closes https://github.com/interlay/interbtc/issues/1015
=> chore: re-run script to fetch Bitcoin block headers

crates/loans/src/lib.rs, crates/loans/src/tests.rs, crates/loans/src/tests/liquidate_borrow.rs
Closes #1066. The problem and solution has been mentioned in the issue.
=> fix: Handle AlreadyActiveMarket corner case in activate_market extrinsic

.github/PULL_REQUEST_TEMPLATE/pull_request.md, .github/PULL_REQUEST_TEMPLATE/release.md
Adds PR templates for basic changes and the release process.
=> feat: add pull request templates

.github/workflows/notify-breaking.yml
- Adds a new github action to notifiy team of breaking changes on the chain
=> feat: notify team of breaking changes on discord

.github/workflows/benchmark.yml, scripts/benchmark.sh
=> fix: leave bench args unset

scripts/benchmark.sh
=> fix: benchmark runtime path

scripts/benchmark.sh
=> chore: debug benchmark

Cargo.lock, crates/bitcoin/src/compat.rs
Suggested changes for simplifying type conversions
=> chore: use TryFrom for rust-bitcoin conversions
